import type { AgentHealthSnapshot, AgentRuntimeMetrics, OrchestrationHealth, QueuedTask, TaskExecutionRecord } from "./types";
import { clamp, nowIso } from "./utils";
export function calculateAgentMetrics(agentId: string, records: TaskExecutionRecord[], queued: QueuedTask[], heartbeat?: string): AgentHealthSnapshot {
  const mine = records.filter((record) => record.agentId === agentId); const successes = mine.filter((record) => record.status === "completed").length; const failures = mine.filter((record) => record.status === "failed").length; const executionCount = mine.length; const averageRuntimeMs = executionCount ? Math.round(mine.reduce((sum, record) => sum + record.runtimeMs, 0) / executionCount) : 0; const queuedWork = queued.filter((task) => task.agentId === agentId && task.status === "queued").length; const running = queued.some((task) => task.agentId === agentId && task.status === "running"); const successRate = executionCount ? Math.round((successes / executionCount) * 100) : 100; const failureRate = executionCount ? Math.round((failures / executionCount) * 100) : 0; const healthScore = clamp(successRate - failureRate - queuedWork * 2 + (heartbeat ? 5 : 0));
  return { agentId, executionCount, successCount: successes, failureCount: failures, successRate, failureRate, averageRuntimeMs, lastExecutionAt: mine.at(-1)?.completedAt ?? mine.at(-1)?.startedAt, queuedWork, currentActivity: running ? "running" : queuedWork ? "queued" : "idle", healthScore, availability: running ? "running" : "idle", health: healthScore >= 80 ? "healthy" : healthScore >= 50 ? "degraded" : "unhealthy", lastHeartbeatAt: heartbeat };
}
export function calculateSystemHealth(agentCount: number, snapshots: AgentRuntimeMetrics[], queued: QueuedTask[], history: TaskExecutionRecord[]): OrchestrationHealth {
  const completed = history.filter((record) => record.status === "completed").length; const failed = history.filter((record) => record.status === "failed").length; const runningAgents = snapshots.filter((snapshot) => snapshot.currentActivity === "running").length; const healthScore = agentCount ? Math.round(snapshots.reduce((sum, snapshot) => sum + snapshot.healthScore, 0) / Math.max(snapshots.length, 1)) : 100; return { status: healthScore >= 80 ? "healthy" : healthScore >= 50 ? "degraded" : "unhealthy", registeredAgents: agentCount, runningAgents, idleAgents: Math.max(agentCount - runningAgents, 0), queuedWork: queued.filter((task) => task.status === "queued").length, completedWork: completed, failedWork: failed, throughputPerMinute: completed, healthScore, generatedAt: nowIso() };
}
