import { connectorError } from "../../../connector-errors";
import type { ConnectorExecutionRequest, ConnectorExecutionResult } from "../../../connector-types";
import { readiness } from "../shared/intelligence";
import { persistGoogleWorkspaceSnapshot } from "../shared/persistence";
import { recordGoogleWorkspaceTelemetry } from "../shared/telemetry";
import { requireWorkspaceEnvelope } from "../shared/types";
import { evaluateDrivePolicy } from "./policy";
import { validateDriveRequest } from "./validator";
const sampleCounters: Record<string, number> = {"storage":64,"folders":28,"duplicates":2,"stale":4,"orphaned":1};
export async function executeDriveOperation(request: ConnectorExecutionRequest): Promise<ConnectorExecutionResult> { const started=Date.now(); const validation=validateDriveRequest(request); if(!validation.valid) return { connectorId:'google-drive', operationId:request.operationId, success:false, error:connectorError('GOOGLE_WORKSPACE_CONTEXT_INVALID', validation.errors.join(' ')), durationMs:Date.now()-started, correlationId:request.context.correlationId }; const approved = request.input?.approved === true || request.context.metadata?.approved === true; const policy=evaluateDrivePolicy(request.operationId, approved); if(!policy.allowed){ recordGoogleWorkspaceTelemetry({service:'drive', operationId:request.operationId, status:'denied', durationMs:Date.now()-started, correlationId:request.context.correlationId, at:new Date().toISOString()}); return { connectorId:'google-drive', operationId:request.operationId, success:false, error:connectorError('APPROVAL_REQUIRED', policy.reason), durationMs:Date.now()-started, correlationId:request.context.correlationId }; } const envelope=requireWorkspaceEnvelope(request.context,'google-drive',request.operationId); const snapshot=persistGoogleWorkspaceSnapshot(readiness('drive', sampleCounters)); const durationMs=Date.now()-started; recordGoogleWorkspaceTelemetry({service:'drive', operationId:request.operationId, status:'success', durationMs, correlationId:request.context.correlationId, at:new Date().toISOString(), details:{readinessScore:snapshot.readinessScore}}); return { connectorId:'google-drive', operationId:request.operationId, success:true, output:{ service:'drive', operation:request.operationId, envelope, snapshot, approval:policy, deterministicIntelligence:true, networkCalls:0 }, durationMs, correlationId:request.context.correlationId }; }
