import type { DashboardData, Organization } from "../dashboard/queries";
import type { KnowledgeHealthReport } from "../knowledge";
import type { GovernanceSnapshot } from "../governance";
import type { InstalledPlugin } from "../plugins";

export type ScenarioType = "grant_denied" | "hire_volunteers" | "revenue_doubles" | "production_increase" | "legal_case_surge" | "ai_provider_unavailable" | "knowledge_vault_growth" | "custom";
export type SimulationInput = { id: string; name: string; type: ScenarioType; assumptions: Record<string, number | string | boolean>; strategy?: string };
export type TwinKpi = { name: string; current: number; expected: number; delta: number; unit: string };
export type SimulationResult = { id: string; name: string; strategy: string; expectedKpis: TwinKpi[]; risks: string[]; confidence: number; bottlenecks: string[]; resourceImpact: string[]; budgetImpact: string[]; approvalImpact: string[]; timelineImpact: string[]; recommendedActions: string[]; alternativeScenarios: string[]; score: { cost: number; risk: number; time: number; workload: number; funding: number; successProbability: number }; governance: { simulationOnly: true; connectorWrites: false; externalActions: false; approvalsBypassed: false } };
export type DigitalTwin = { organization: Pick<Organization, "id" | "name" | "mission" | "industry" | "status"> | null; departments: string[]; projects: number; workflows: number; people: number; agents: number; tasks: number; approvals: number; funding: { pendingApprovals: number; sponsorSignals: number; grantSignals: number }; budgets: { monthlyOperatingEstimate: number; approvalLockedEstimate: number }; knowledgeGraph: { providers: number; indexedDocuments: number; health: string }; plugins: { enabled: number; simulationModelPlugins: string[] }; connectors: { readOnlyContext: true; writesDisabled: true }; kpis: TwinKpi[]; policies: string[]; generatedAt: string };
export type SimulationComparison = { scenarios: SimulationResult[]; recommendedScenario: SimulationResult | null; comparison: Array<{ id: string; name: string; cost: number; risk: number; time: number; workload: number; funding: number; successProbability: number; confidence: number }> };
export type SimulationDashboard = { activeSimulations: number; recommendedScenario: string; predictedBottlenecks: string[]; projectedKpiChanges: TwinKpi[]; confidence: number };

const departments = ["Executive", "Legal", "Funding", "Finance", "Research", "Knowledge", "Media", "Operations", "Property", "Education", "Partnerships", "Volunteers"];
const closed = new Set(["closed", "complete", "completed", "archived", "done", "approved", "rejected"]);
const active = (status?: string | null) => !closed.has(String(status ?? "").toLowerCase());
const num = (value: unknown, fallback = 0) => typeof value === "number" && Number.isFinite(value) ? value : fallback;

export function buildDigitalTwin(input: { organization?: Organization | null; dashboard: DashboardData; knowledgeHealth: KnowledgeHealthReport; governance: GovernanceSnapshot; workflows: unknown[]; plugins: InstalledPlugin[]; now?: Date }): DigitalTwin {
  const tasks = input.dashboard.tasks.filter((task) => active(task.status)).length;
  const approvals = input.dashboard.approvals.filter((approval) => approval.status === "pending").length;
  const blocked = input.dashboard.tasks.filter((task) => String(task.status ?? "").toLowerCase() === "blocked").length;
  const providerList = [...input.knowledgeHealth.providers.memory, ...input.knowledgeHealth.providers.search, ...input.knowledgeHealth.providers.indexing];
  const providers = providerList.length;
  const indexedDocuments = input.knowledgeHealth.indexedDocuments;
  const agents = input.dashboard.agents.filter((agent) => active(agent.status)).length;
  return { organization: input.organization ? { id: input.organization.id, name: input.organization.name, mission: input.organization.mission, industry: input.organization.industry, status: input.organization.status } : null, departments, projects: input.dashboard.projects.filter((project) => active(project.status)).length, workflows: input.workflows.length, people: input.dashboard.memberships.length, agents, tasks, approvals, funding: { pendingApprovals: approvals, sponsorSignals: input.dashboard.auditLogs.filter((log) => log.action.toLowerCase().includes("sponsor")).length, grantSignals: input.dashboard.auditLogs.filter((log) => log.action.toLowerCase().includes("grant")).length }, budgets: { monthlyOperatingEstimate: Math.round((tasks * 120) + (agents * 350) + (input.dashboard.projects.length * 500)), approvalLockedEstimate: approvals * 250 }, knowledgeGraph: { providers, indexedDocuments, health: input.knowledgeHealth.synchronizationStatus }, plugins: { enabled: input.plugins.filter((plugin) => plugin.enabled).length, simulationModelPlugins: input.plugins.filter((plugin) => plugin.enabled && (plugin.capabilities.includes("automation") || plugin.capabilities.includes("knowledge") || plugin.capabilities.includes("dashboard"))).map((plugin) => plugin.id) }, connectors: { readOnlyContext: true, writesDisabled: true }, kpis: [{ name: "Active tasks", current: tasks, expected: tasks, delta: 0, unit: "tasks" }, { name: "Pending approvals", current: approvals, expected: approvals, delta: 0, unit: "approvals" }, { name: "Blocked work", current: blocked, expected: blocked, delta: 0, unit: "tasks" }, { name: "Knowledge index", current: indexedDocuments, expected: indexedDocuments, delta: 0, unit: "documents" }], policies: input.governance.policies.map((policy) => policy.name), generatedAt: (input.now ?? new Date()).toISOString() };
}

export function simulateScenario(twin: DigitalTwin, scenario: SimulationInput): SimulationResult {
  const volunteers = num(scenario.assumptions.volunteers); const revenueMultiplier = num(scenario.assumptions.revenueMultiplier, 1); const newCases = num(scenario.assumptions.newCases); const extraFiles = num(scenario.assumptions.extraFiles); const productionMultiplier = num(scenario.assumptions.productionMultiplier, 1);
  let workload = twin.tasks + Math.ceil(newCases / 25) + Math.ceil(extraFiles / 100000) + Math.ceil((productionMultiplier - 1) * 10) - volunteers * 3;
  let funding = Math.round((twin.funding.grantSignals * 1000 + twin.funding.sponsorSignals * 750) * revenueMultiplier);
  let risk = 25 + twin.approvals * 5 + Math.ceil(newCases / 50) + Math.ceil(extraFiles / 500000);
  if (scenario.type === "grant_denied") { funding -= num(scenario.assumptions.grantAmount, 10000); risk += 12; }
  if (scenario.type === "ai_provider_unavailable") { risk += 18; workload += 4; }
  if (scenario.type === "hire_volunteers") risk -= volunteers * 4;
  workload = Math.max(0, workload); risk = Math.max(1, Math.min(99, risk));
  const confidence = Math.max(55, Math.min(94, 88 - Math.ceil(extraFiles / 1000000) - Math.ceil(newCases / 200) - (scenario.type === "custom" ? 8 : 0)));
  const expectedKpis = twin.kpis.map((kpi) => kpi.name === "Active tasks" ? { ...kpi, expected: workload, delta: workload - kpi.current } : kpi.name === "Pending approvals" ? { ...kpi, expected: twin.approvals + Math.ceil(risk / 30), delta: Math.ceil(risk / 30) } : kpi.name === "Knowledge index" ? { ...kpi, expected: twin.knowledgeGraph.indexedDocuments + extraFiles, delta: extraFiles } : kpi);
  return { id: scenario.id, name: scenario.name, strategy: scenario.strategy ?? scenario.type.replaceAll("_", " "), expectedKpis, risks: risk > 70 ? ["High operational load", "Approval queue pressure", "Confidence degradation"] : ["Monitor assumptions", "Keep human review on critical decisions"], confidence, bottlenecks: [workload > twin.tasks ? "Department workload" : "Current throughput", twin.approvals ? "Approval queue" : "No approval bottleneck", extraFiles ? "Knowledge indexing capacity" : "Knowledge evidence review"], resourceImpact: [`Workload changes by ${workload - twin.tasks} task-equivalent units.`, volunteers ? `${volunteers} volunteers reduce queue pressure.` : "No new staffing assumed."], budgetImpact: [`Projected funding impact: $${funding.toLocaleString()}.`, `Estimated operating cost score: ${Math.max(1, workload * 100)}.`], approvalImpact: ["Simulation does not bypass approvals.", `Expected pending approval load: ${twin.approvals + Math.ceil(risk / 30)}.`], timelineImpact: [`Estimated time score ${Math.max(1, workload * 2 + risk)}.`], recommendedActions: ["Review scenario with Executive Command before execution.", "Attach Knowledge Graph evidence to assumptions.", "Route legal, finance, connector, outreach, and filing actions through approvals."], alternativeScenarios: ["Lower workload option", "Higher funding option", "Provider fallback option"], score: { cost: Math.max(1, workload * 100), risk, time: Math.max(1, workload * 2 + risk), workload, funding, successProbability: Math.max(1, 100 - risk + Math.floor(confidence / 10)) }, governance: { simulationOnly: true, connectorWrites: false, externalActions: false, approvalsBypassed: false } };
}

export function compareScenarios(twin: DigitalTwin, scenarios: SimulationInput[]): SimulationComparison { const results = scenarios.map((scenario) => simulateScenario(twin, scenario)); const recommendedScenario = [...results].sort((a, b) => (b.score.successProbability + b.confidence + b.score.funding / 1000) - (a.score.successProbability + a.confidence + a.score.funding / 1000))[0] ?? null; return { scenarios: results, recommendedScenario, comparison: results.map(({ id, name, score, confidence }) => ({ id, name, ...score, confidence })) }; }
export function buildSimulationDashboard(comparison: SimulationComparison): SimulationDashboard { return { activeSimulations: comparison.scenarios.length, recommendedScenario: comparison.recommendedScenario?.name ?? "No scenario recommended", predictedBottlenecks: Array.from(new Set(comparison.scenarios.flatMap((scenario) => scenario.bottlenecks))).slice(0, 5), projectedKpiChanges: comparison.recommendedScenario?.expectedKpis ?? [], confidence: comparison.recommendedScenario?.confidence ?? 0 }; }
export function defaultExecutiveScenarios(twin: DigitalTwin): SimulationInput[] { return [{ id: "scenario-grant-denied", name: "Grant A denied", type: "grant_denied", assumptions: { grantAmount: 25000 } }, { id: "scenario-two-volunteers", name: "Hire two volunteers", type: "hire_volunteers", assumptions: { volunteers: 2 } }, { id: "scenario-sponsor-double", name: "Sponsor revenue doubles", type: "revenue_doubles", assumptions: { revenueMultiplier: 2 } }, { id: "scenario-legal-surge", name: "Legal receives 500 cases", type: "legal_case_surge", assumptions: { newCases: 500 } }, { id: "scenario-knowledge-growth", name: "Mac Knowledge Vault indexes 2M files", type: "knowledge_vault_growth", assumptions: { extraFiles: 2_000_000, currentIndex: twin.knowledgeGraph.indexedDocuments } }]; }
