import { revalidatePath } from "next/cache";
import { requireActiveOrganization, organizationFilter } from "../../lib/activeOrganization";
import { formBool, formValue, getRows, supabaseRequest } from "../../lib/supabase/data";
import { requireSession } from "../../lib/supabase/server";

export default async function TasksPage() {
  const { session, activeOrganization } = await requireActiveOrganization();
  async function createTask(fd: FormData) { "use server"; const s = requireSession(); const organizationId = formValue(fd, "organization_id"); await supabaseRequest("tasks", { token: s.access_token, method: "POST", body: { title: formValue(fd, "title"), description: formValue(fd, "description"), priority: formValue(fd, "priority") ?? "medium", status: formValue(fd, "status") ?? "todo", organization_id: organizationId, project_id: formValue(fd, "project_id"), assigned_user_id: formValue(fd, "assigned_user_id"), assigned_agent_id: formValue(fd, "assigned_agent_id"), due_at: formValue(fd, "due_at"), dependencies: (formValue(fd, "dependencies") ?? "").split(",").map((x) => x.trim()).filter(Boolean), approval_required: formBool(fd, "approval_required"), completion_date: formValue(fd, "completion_date") } }); revalidatePath("/tasks"); }
  const tasks = await getRows<Record<string, any>>("tasks", session.access_token, `?select=*&${organizationFilter(activeOrganization?.id)}&order=due_at.asc`);
  return <main className="shell"><section className="pageHeader panel"><p className="eyebrow">Task Engine · {activeOrganization?.name ?? "No active organization"}</p><h1>Tasks</h1></section><form action={createTask} className="panel crudForm"><input type="hidden" name="organization_id" value={activeOrganization?.id ?? ""} />{["title", "description", "priority", "status", "project_id", "assigned_user_id", "assigned_agent_id", "due_at", "dependencies", "completion_date"].map((f) => <label key={f}>{f.replaceAll("_", " ")}<input name={f} /></label>)}<label className="check"><input type="checkbox" name="approval_required" /> Approval required</label><button className="button primary">Create task</button></form><section className="recordGrid">{tasks.map((t) => <article className="panel recordCard" key={t.id}><h2>{t.title}</h2><p>{t.priority} · {t.status} · due {t.due_at ?? "unscheduled"}</p></article>)}</section></main>;
}
