import type { ExecutionPlan, ExecutionTask, PlanningInput, RollbackRequirement } from "./execution-plan";
import { evaluateApprovalPolicy } from "./approval-policies";
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const uniq = <T,>(items: T[]) => Array.from(new Set(items));
export class ExecutionPlanner { createPlan(input: PlanningInput): ExecutionPlan { const now = new Date(input.now ?? Date.now()); const orgId = input.organization?.id; const tasks: ExecutionTask[] = [];
  if (input.platformHealth?.status !== "healthy") tasks.push(this.task("diagnose-platform-health", "Diagnose platform health", "Review deterministic health warnings before autonomous work.", "diagnostic", [], 55, ["observability:read"], "manual_review"));
  for (const w of input.workflows ?? []) if (w.status !== "active") tasks.push(this.task(`review-workflow-${slug(w.id)}`, `Review workflow ${w.name}`, "Validate workflow status before scheduling.", "workflow", tasks.map(t=>t.id).slice(-1), 35, ["workflow:read"], "compensation"));
  for (const tool of input.runtimeTools ?? []) if (tool.deterministic) tasks.push(this.task(`simulate-runtime-${slug(tool.id)}`, `Simulate ${tool.name}`, "Prepare deterministic runtime simulation only; no live execution.", "runtime", [], 25, tool.requiredPermissions ?? ["runtime:read"], "none"));
  for (const c of input.connectors ?? []) tasks.push(this.task(`inspect-connector-${slug(c.id)}`, `Inspect ${c.name}`, "Inspect connector capabilities and restrictions without network calls.", "connector", [], c.health?.status === "healthy" ? 30 : 50, ["connectors:read"], "manual_review"));
  if ((input.knowledgeHealth?.failedIndexingJobs?.length ?? 0) > 0) tasks.push(this.task("recover-knowledge-indexing", "Plan knowledge indexing recovery", "Create recovery plan for failed indexing jobs.", "knowledge", [], 45, ["knowledge:read"], "compensation"));
  if (!tasks.length) tasks.push(this.task("autonomy-readiness-check", "Autonomy readiness check", "Confirm deterministic readiness and approval boundaries.", "diagnostic", [], 15, ["dashboard:read"], "none"));
  const id = `plan-${orgId ?? "global"}-${now.toISOString().slice(0,10)}-${tasks.length}`;
  const evaluated = tasks.map((task) => { const policy = evaluateApprovalPolicy({ planId: id, taskId: task.id, organizationId: orgId, riskScore: task.estimatedImpact, impactScore: task.estimatedImpact, requiredCapabilities: task.requiredCapabilities, touchesExternalSystem: task.type === "connector", dataClassification: task.type === "connector" ? "confidential" : "internal" }); return { ...task, approvalLevel: policy.level, status: policy.level === "automatic" ? "planned" as const : "waiting_approval" as const }; });
  return { id, organizationId: orgId, title: "Autonomous operations execution plan", summary: `${evaluated.length} deterministic tasks planned; live execution disabled.`, createdAt: now.toISOString(), updatedAt: now.toISOString(), source: input.source ?? "dashboard", tasks: evaluated, requiredApprovals: uniq(evaluated.map(t => t.approvalLevel).filter(a => a !== "automatic")), timeline: evaluated.map((t, i) => ({ taskId: t.id, order: i + 1, earliestStartOffsetMs: i * 60_000, latestFinishOffsetMs: (i + 1) * 60_000 + t.durationMsEstimate, dependsOn: t.dependencies })), confidence: Math.max(50, 95 - (input.platformHealth?.errors?.length ?? 0) * 10 - (input.operatingHistory?.failedEvents?.length ?? 0) * 5), estimatedImpact: Math.round(evaluated.reduce((s,t)=>s+t.estimatedImpact,0)/evaluated.length), rollbackRequirements: uniq(evaluated.map(t => t.rollbackRequirement)), status: evaluated.some(t => t.status === "waiting_approval") ? "awaiting_approval" : "approved" }; }
 private task(id: string, title: string, description: string, type: ExecutionTask["type"], dependencies: string[], estimatedImpact: number, requiredCapabilities: string[], rollbackRequirement: RollbackRequirement): ExecutionTask { return { id, title, description, type, dependencies, estimatedImpact, approvalLevel: "automatic", status: "planned", requiredCapabilities, rollbackRequirement, durationMsEstimate: 30_000 }; }}
export const executionPlanner = new ExecutionPlanner();
