import { buildDelegationQueue } from "./chief-of-staff-delegation";
import { emptyChiefOfStaffMemory, memoryFromSnapshot, recordChiefOfStaffSnapshot } from "./chief-of-staff-memory";
import { buildBriefing, buildFollowUps } from "./chief-of-staff-planner";
import { chiefOfStaffTelemetry } from "./chief-of-staff-telemetry";
import type { ChiefOfStaffContext, ChiefOfStaffSnapshot } from "./chief-of-staff-types";
import { validateChiefOfStaffContext, validateChiefOfStaffSnapshot } from "./chief-of-staff-validator";
import type { PersistenceContext } from "../../persistence";
export class ChiefOfStaffRuntime { async synthesize(ctx: ChiefOfStaffContext, persistence?: PersistenceContext): Promise<ChiefOfStaffSnapshot> { const errors = validateChiefOfStaffContext(ctx); if (errors.length) throw new Error(`Invalid Chief of Staff context: ${errors.join(", ")}`); const briefing = buildBriefing(ctx); const delegationQueue = buildDelegationQueue(ctx); const followUpQueue = buildFollowUps(ctx); const generatedAt = (ctx.now ?? new Date()).toISOString(); const snapshot: ChiefOfStaffSnapshot = { briefing, dailyPriorities: ctx.executiveIntelligence.priorities, criticalRisks: ctx.executiveIntelligence.risks.filter((r) => r.severity === "critical" || r.severity === "high"), delegationQueue, executiveRecommendations: ctx.executiveIntelligence.recommendations, approvalQueue: delegationQueue.filter((d) => d.approvals.length), followUpQueue, strategicOpportunities: ctx.executiveIntelligence.opportunities, executiveTimeline: ctx.executiveIntelligence.timeline, memory: emptyChiefOfStaffMemory(generatedAt), telemetry: chiefOfStaffTelemetry.summary(), generatedAt }; snapshot.memory = memoryFromSnapshot(snapshot); const snapshotErrors = validateChiefOfStaffSnapshot(snapshot); if (snapshotErrors.length) throw new Error(snapshotErrors.join(", ")); chiefOfStaffTelemetry.record("briefing", briefing.summary); delegationQueue.forEach((d) => chiefOfStaffTelemetry.record("delegation", d.title, { ownerAgent: d.ownerAgent, priority: d.priority })); if (snapshot.approvalQueue.length) chiefOfStaffTelemetry.record("approval_request", `${snapshot.approvalQueue.length} delegation approvals required.`); if (followUpQueue.length) chiefOfStaffTelemetry.record("follow_up", `${followUpQueue.length} follow-ups generated.`); chiefOfStaffTelemetry.record("priority_generation", `${snapshot.dailyPriorities.length} priorities synchronized from Executive Intelligence.`); snapshot.telemetry = chiefOfStaffTelemetry.summary(); if (persistence) await recordChiefOfStaffSnapshot(persistence, snapshot); return snapshot; }}
export const chiefOfStaffRuntime = new ChiefOfStaffRuntime();
