import { connectorError } from "../../../connector-errors";
import type { ConnectorExecutionRequest, ConnectorExecutionResult } from "../../../connector-types";
import { readiness } from "../shared/intelligence";
import { persistGoogleWorkspaceSnapshot } from "../shared/persistence";
import { recordGoogleWorkspaceTelemetry } from "../shared/telemetry";
import { requireWorkspaceEnvelope } from "../shared/types";
import { evaluateCalendarPolicy } from "./policy";
import { validateCalendarRequest } from "./validator";
const sampleCounters: Record<string, number> = {"meetings":5,"conflicts":1,"availability":3,"idleBlocks":2};
export async function executeCalendarOperation(request: ConnectorExecutionRequest): Promise<ConnectorExecutionResult> { const started=Date.now(); const validation=validateCalendarRequest(request); if(!validation.valid) return { connectorId:'google-calendar', operationId:request.operationId, success:false, error:connectorError('GOOGLE_WORKSPACE_CONTEXT_INVALID', validation.errors.join(' ')), durationMs:Date.now()-started, correlationId:request.context.correlationId }; const approved = request.input?.approved === true || request.context.metadata?.approved === true; const policy=evaluateCalendarPolicy(request.operationId, approved); if(!policy.allowed){ recordGoogleWorkspaceTelemetry({service:'calendar', operationId:request.operationId, status:'denied', durationMs:Date.now()-started, correlationId:request.context.correlationId, at:new Date().toISOString()}); return { connectorId:'google-calendar', operationId:request.operationId, success:false, error:connectorError('APPROVAL_REQUIRED', policy.reason), durationMs:Date.now()-started, correlationId:request.context.correlationId }; } const envelope=requireWorkspaceEnvelope(request.context,'google-calendar',request.operationId); const snapshot=persistGoogleWorkspaceSnapshot(readiness('calendar', sampleCounters)); const durationMs=Date.now()-started; recordGoogleWorkspaceTelemetry({service:'calendar', operationId:request.operationId, status:'success', durationMs, correlationId:request.context.correlationId, at:new Date().toISOString(), details:{readinessScore:snapshot.readinessScore}}); return { connectorId:'google-calendar', operationId:request.operationId, success:true, output:{ service:'calendar', operation:request.operationId, envelope, snapshot, approval:policy, deterministicIntelligence:true, networkCalls:0 }, durationMs, correlationId:request.context.correlationId }; }
