import type { ConnectorExecutionRequest, ConnectorExecutionResult } from "../../connector-types";
import { connectorError } from "../../connector-errors";
import { githubClient } from "./github-client";
import { sanitizeGitHubError } from "./github-errors";
import { evaluateGitHubPolicy } from "./github-policy";
import { recordGitHubTelemetry } from "./github-telemetry";
import { validateGitHubRequest } from "./github-validator";
import type { GitHubRuntimeInput } from "./github-types";
const qs = (input: GitHubRuntimeInput) => new URLSearchParams(Object.entries(input).filter(([,v]) => v !== undefined && typeof v !== "object").map(([k,v]) => [k, String(v)])).toString();
function ownerRepo(i: GitHubRuntimeInput) { const owner = i.owner ?? i.organization; if (!owner || !i.repo) throw new Error("owner/organization and repo are required."); return `/repos/${owner}/${i.repo}`; }
export async function executeGitHubOperation(request: ConnectorExecutionRequest): Promise<ConnectorExecutionResult> { const started = Date.now(); const input = (request.input ?? {}) as GitHubRuntimeInput; const validation = validateGitHubRequest(request); if (!validation.valid) return { connectorId: "github", operationId: request.operationId, success: false, error: connectorError("GITHUB_CONTEXT_INVALID", validation.errors.join(" ")), durationMs: Date.now()-started, correlationId: request.context.correlationId }; const policy = evaluateGitHubPolicy(request.operationId, input.approved === true); if (!policy.allowed) { recordGitHubTelemetry({ operationId: request.operationId, status: "denied", durationMs: Date.now()-started, correlationId: request.context.correlationId, at: new Date().toISOString() }); return { connectorId: "github", operationId: request.operationId, success: false, error: connectorError("APPROVAL_REQUIRED", policy.reason), durationMs: Date.now()-started, correlationId: request.context.correlationId }; }
 try { let path = "/rate_limit"; const p = qs({ per_page: input.per_page ?? 30, page: input.page ?? 1, state: input.state }); switch (request.operationId) { case "repos.list": path = `/orgs/${input.organization}/repos?${p}`; break; case "repos.read": path = ownerRepo(input); break; case "branches.list": path = `${ownerRepo(input)}/branches?${p}`; break; case "tags.list": path = `${ownerRepo(input)}/tags?${p}`; break; case "pulls.list": path = `${ownerRepo(input)}/pulls?${p}`; break; case "pulls.read": case "pulls.merge_status": case "pulls.review_status": path = `${ownerRepo(input)}/pulls/${input.pull_number}`; break; case "issues.list": path = `${ownerRepo(input)}/issues?${p}`; break; case "issues.read": path = `${ownerRepo(input)}/issues/${input.issue_number}`; break; case "labels.list": path = `${ownerRepo(input)}/labels?${p}`; break; case "commits.list": path = `${ownerRepo(input)}/commits?${p}`; break; case "commits.read": path = `${ownerRepo(input)}/commits/${input.sha}`; break; case "actions.runs": case "actions.status": path = `${ownerRepo(input)}/actions/runs?${p}`; break; case "actions.failed_jobs": path = `${ownerRepo(input)}/actions/runs/${input.run_id}/jobs?filter=latest`; break; case "actions.successful_jobs": path = `${ownerRepo(input)}/actions/runs/${input.run_id}/jobs?filter=latest`; break; case "releases.list": path = `${ownerRepo(input)}/releases?${p}`; break; case "releases.latest": path = `${ownerRepo(input)}/releases/latest`; break; case "search.repositories": path = `/search/repositories?q=${encodeURIComponent(String(input.query ?? "org:" + input.organization))}`; break; case "search.code": path = `/search/code?q=${encodeURIComponent(String(input.query ?? "org:" + input.organization))}`; break; case "search.issues": path = `/search/issues?q=${encodeURIComponent(String(input.query ?? "org:" + input.organization))}`; break; case "deployments.list": path = `${ownerRepo(input)}/deployments?${p}`; break; case "pulls.create": path = `${ownerRepo(input)}/pulls`; break; case "pulls.update": path = `${ownerRepo(input)}/pulls/${input.pull_number}`; break; case "issues.create": path = `${ownerRepo(input)}/issues`; break; case "issues.update": path = `${ownerRepo(input)}/issues/${input.issue_number}`; break; }
 const mutating = ["pulls.create","pulls.update","issues.create","issues.update"].includes(request.operationId); const data = await githubClient.request(path, mutating ? { method: request.operationId.endsWith("create") ? "POST" : "PATCH", body: JSON.stringify(input) } : {}); const durationMs = Date.now()-started; recordGitHubTelemetry({ operationId: request.operationId, status: "success", durationMs, correlationId: request.context.correlationId, at: new Date().toISOString(), details: { rateLimit: githubClient.lastRateLimit } }); return { connectorId: "github", operationId: request.operationId, success: true, output: { data, rateLimit: githubClient.lastRateLimit, executionHistory: { runtimeSessionId: request.context.runtimeSessionId, policy: policy.reason } }, durationMs, correlationId: request.context.correlationId }; } catch (e) { const durationMs = Date.now()-started; const safe = sanitizeGitHubError(e); recordGitHubTelemetry({ operationId: request.operationId, status: "failure", durationMs, correlationId: request.context.correlationId, at: new Date().toISOString(), details: safe }); return { connectorId: "github", operationId: request.operationId, success: false, error: connectorError(safe.code, safe.message), durationMs, correlationId: request.context.correlationId }; } }
