import { connectorError } from "../../../connector-errors";
import type { ConnectorExecutionRequest, ConnectorExecutionResult } from "../../../connector-types";
import { readiness } from "../shared/intelligence";
import { persistGoogleWorkspaceSnapshot } from "../shared/persistence";
import { recordGoogleWorkspaceTelemetry } from "../shared/telemetry";
import { requireWorkspaceEnvelope } from "../shared/types";
import { evaluateGmailPolicy } from "./policy";
import { validateGmailRequest } from "./validator";
const sampleCounters: Record<string, number> = {"unread":12,"overdue":3,"drafts":2,"vip":1};
export async function executeGmailOperation(request: ConnectorExecutionRequest): Promise<ConnectorExecutionResult> { const started=Date.now(); const validation=validateGmailRequest(request); if(!validation.valid) return { connectorId:'gmail', operationId:request.operationId, success:false, error:connectorError('GOOGLE_WORKSPACE_CONTEXT_INVALID', validation.errors.join(' ')), durationMs:Date.now()-started, correlationId:request.context.correlationId }; const approved = request.input?.approved === true || request.context.metadata?.approved === true; const policy=evaluateGmailPolicy(request.operationId, approved); if(!policy.allowed){ recordGoogleWorkspaceTelemetry({service:'gmail', operationId:request.operationId, status:'denied', durationMs:Date.now()-started, correlationId:request.context.correlationId, at:new Date().toISOString()}); return { connectorId:'gmail', operationId:request.operationId, success:false, error:connectorError('APPROVAL_REQUIRED', policy.reason), durationMs:Date.now()-started, correlationId:request.context.correlationId }; } const envelope=requireWorkspaceEnvelope(request.context,'gmail',request.operationId); const snapshot=persistGoogleWorkspaceSnapshot(readiness('gmail', sampleCounters)); const durationMs=Date.now()-started; recordGoogleWorkspaceTelemetry({service:'gmail', operationId:request.operationId, status:'success', durationMs, correlationId:request.context.correlationId, at:new Date().toISOString(), details:{readinessScore:snapshot.readinessScore}}); return { connectorId:'gmail', operationId:request.operationId, success:true, output:{ service:'gmail', operation:request.operationId, envelope, snapshot, approval:policy, deterministicIntelligence:true, networkCalls:0 }, durationMs, correlationId:request.context.correlationId }; }
