import type { Budget,Donation,GrantRevenue,SponsorRecord,Invoice,CashFlowItem,ComplianceReminder,FinanceReport } from "./finance-types";
export const demoBudgets:Budget[]=[{id:"b-annual",organizationId:"demo",name:"Annual operating budget",scope:"annual",categoryId:"operations",period:"2026",allocated:500000,committed:210000,spent:180000,forecast:520000,restriction:"unrestricted"},{id:"b-grant",organizationId:"demo",name:"Restricted youth program",scope:"project",categoryId:"restricted-grants",project:"Youth AI Lab",period:"2026",allocated:125000,committed:60000,spent:42000,forecast:118000,restriction:"restricted"}];
export const demoDonations:Donation[]=[{id:"d-1",donor:"Avery Foundation",campaign:"Annual Fund",designation:"unrestricted",amount:25000,receivedAt:"2026-05-01",receiptStatus:"sent",acknowledgementStatus:"sent",reportingStatus:"complete"},{id:"d-2",donor:"Community Donor",campaign:"Youth AI Lab",designation:"restricted",amount:5000,receivedAt:"2026-06-20",receiptStatus:"needed",acknowledgementStatus:"needed",reportingStatus:"pending"}];
export const demoGrantRevenue:GrantRevenue[]=[{id:"gr-1",grantId:"grant-youth-ai",funder:"City Innovation Fund",status:"awarded",amount:100000,received:40000,restrictions:["Youth AI Lab only"],reportDueAt:"2026-09-30"},{id:"gr-2",grantId:"grant-capacity",funder:"Regional Foundation",status:"pending",amount:75000,received:0,restrictions:["Capacity building"]}];
export const demoSponsors:SponsorRecord[]=[{id:"s-1",sponsor:"Northstar Tech",agreement:"Gold sponsor",invoices:2,deliverables:["logo placement","quarterly impact note"],renewalAt:"2026-11-15",balance:15000,status:"watch"}];
export const demoInvoices:Invoice[]=[{id:"ar-1",party:"Northstar Tech",kind:"accounts_receivable",amount:15000,dueAt:"2026-07-15",status:"sent"},{id:"ap-1",party:"Cloud Vendor",kind:"accounts_payable",amount:4200,dueAt:"2026-07-05",status:"pending_approval"}];
export const demoCashFlow:CashFlowItem[]=[{id:"cf-1",label:"Sponsor receivable",kind:"income",amount:15000,date:"2026-07-15",source:"sponsorships"},{id:"cf-2",label:"Cloud recurring",kind:"expense",amount:4200,date:"2026-07-05",source:"recurring-expenses"},{id:"cf-3",label:"Grant tranche",kind:"income",amount:30000,date:"2026-08-01",source:"grants",restriction:"restricted"}];
export const demoCompliance:ComplianceReminder[]=[{id:"c-1",type:"grant_reporting",label:"City Innovation Fund Q3 report",dueAt:"2026-09-30",status:"watch"},{id:"c-2",type:"audit_readiness",label:"Prepare audit support packet",dueAt:"2026-12-01",status:"ok"}];
export const demoReports:FinanceReport[]=[{id:"r-1",type:"budget",title:"Budget health summary",period:"2026",status:"ready_for_review"},{id:"r-2",type:"donation",title:"Donation acknowledgement queue",period:"2026-06",status:"draft"}];
