import type { ExecutiveAnalysisContext, ExecutiveRecommendation } from "./executive-types";
const rec=(id:string,severity:ExecutiveRecommendation["severity"],subsystem:ExecutiveRecommendation["subsystem"],title:string,rationale:string,suggestedAction:string,expectedImpact:string,evidence:string[],confidence=0.84):ExecutiveRecommendation=>({id,kind:"recommendation",severity,subsystem,title,rationale,suggestedAction,expectedImpact,evidence,confidence,status:"open",createdAt:new Date().toISOString()});
export function generateRecommendations(ctx: ExecutiveAnalysisContext): ExecutiveRecommendation[]{ const out:ExecutiveRecommendation[]=[];
 if(!ctx.workflows.length) out.push(rec("register-workflows","high","workflows","Register executive workflows","No workflow registrations are available to orchestrate repeated operations.","Register deterministic workflows for approvals, release review, connector checks, and knowledge refresh.","Creates repeatable operating lanes.",["workflow count: 0"]));
 const bad=ctx.connectors.filter(c=>c.health.status!=="healthy"); if(bad.length) out.push(rec("connector-health","high","connectors","Stabilize unhealthy connectors",`${bad.length} connector(s) report degraded health.`,"Run connector diagnostics and disable dependent workflows until health is restored.","Reduces integration failure risk.",bad.map(c=>`${c.name}: ${c.health.status}`)));
 const unused=ctx.runtimeTools.filter(t=>!ctx.runtimeMetrics.toolUsage[t.id]); if(unused.length) out.push(rec("unused-runtime-tools","medium","runtime","Review unused runtime tools",`${unused.length} deterministic runtime tool(s) have no recorded usage.`,"Confirm each tool has an owning workflow or remove stale registrations.","Improves runtime clarity and policy surface.",unused.slice(0,5).map(t=>t.id)));
 if(ctx.diagnostics.findings.length) out.push(rec("diagnostic-findings","high","diagnostics","Resolve diagnostic findings",`${ctx.diagnostics.findings.length} deterministic diagnostic finding(s) are active.`,"Prioritize error findings, then warnings, before preview deployment.","Raises production readiness.",ctx.diagnostics.findings.map(f=>`${f.severity}: ${f.subsystem}/${f.id}`)));
 if(!ctx.knowledgeHealth.indexedDocuments) out.push(rec("knowledge-provider","medium","knowledge","Connect knowledge providers","Knowledge OS has no indexed documents yet.","Add approved organization knowledge sources before relying on memory-backed decisions.","Improves briefing context without embeddings.",["indexed documents: 0"]));
 if(!ctx.organization || ctx.dashboard.memberships.length<=1) out.push(rec("org-coverage","low","organization","Strengthen organization coverage","Organization readiness has limited active membership or context.","Confirm owners, invite operators, and keep organization profile current.","Reduces key-person operational risk.",[`memberships: ${ctx.dashboard.memberships.length}`]));
 if(ctx.runtimeMetrics.policyViolations) out.push(rec("runtime-policy","critical","runtime","Investigate runtime policy violations",`${ctx.runtimeMetrics.policyViolations} policy violation(s) are recorded.`,"Review denied sessions and update allowed permissions or tool policy before retrying.","Prevents unsafe tool execution.",[String(ctx.runtimeMetrics.policyViolations)]));
 if(ctx.operatingHistory.healthSnapshots.length===0) out.push(rec("stale-history","medium","persistence","Persist executive health snapshots","No durable health snapshots are visible for trend analysis.","Write periodic health and executive snapshots through persistence.","Enables operating history trends.",["health snapshots: 0"]));
 return out.slice(0,8); }
