import type { DashboardData } from "../dashboard/queries";
import { buildAttentionQueue, buildRecommendations, getPendingApprovals, getUnhealthyAgents, isTaskOpen } from "../dashboard/intelligence";
import type { AgentCommand, AgentRunContext, AgentRunResult, StructuredAgentOutput } from "../types/agent";
import { buildKnowledgeHealthReport, knowledgeRegistry } from "../knowledge";
import { evaluateReleaseHealth } from "./release-health";
import { getOperatingHistory } from "../persistence";
import { orchestrator } from "../orchestration";
import { workflowEngine } from "../workflows";
import { aiRuntime, createRuntimeContext } from "../runtime";
import { connectorManager } from "../connectors";
import { executiveIntelligenceEngine, explainExecutiveScore } from "../intelligence";
import type { WorkflowExecutionRecord, WorkflowSummary } from "../workflows";

export type CommandAgentInput = { command: string };
export type CommandAgentContext = AgentRunContext<CommandAgentInput, DashboardData>;
export type CommandDefinition = AgentCommand<CommandAgentContext, AgentRunResult>;

function normalizeCommand(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9\s]/g, " ").replace(/\s+/g, " ").trim();
}

function data(context: CommandAgentContext): DashboardData {
  return context.state ?? { organizations: [], projects: [], tasks: [], approvals: [], agents: [], activity: [], health: [], auditLogs: [], memberships: [], userPreferences: [] };
}

function output(title: string, summary: string, sections: StructuredAgentOutput["sections"], recommendations: string[], metadata: Record<string, unknown> = {}): AgentRunResult {
  return { agentId: "executive-command-agent", status: "idle", health: "healthy", errors: [], output: { title, summary, sections, recommendations, metadata } };
}


async function executiveSnapshotFor(context: CommandAgentContext) {
  const d = data(context);
  const { getPlatformHealth, runDiagnostics } = await import("../observability");
  const operatingHistory = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId });
  return executiveIntelligenceEngine.analyze({ organization: d.organizations[0] ?? null, dashboard: d, platformHealth: await getPlatformHealth({ token: context.accessToken, organizationId: context.organizationId }), diagnostics: runDiagnostics(), knowledgeHealth: buildKnowledgeHealthReport(knowledgeRegistry), workflows: workflowEngine.listWorkflows(), runtimeTools: aiRuntime.registry.listTools(), runtimeSessions: aiRuntime.executor.sessions, runtimeMetrics: aiRuntime.telemetry.metrics(), connectors: connectorManager.list(), connectorSessions: connectorManager.runtime.sessions, connectorDiagnostics: connectorManager.diagnostics(), operatingHistory, now: context.now });
}

function workflowSections(record: WorkflowExecutionRecord): StructuredAgentOutput["sections"] {
  return record.result?.sections ?? [{ title: "Workflow errors", items: record.errors.length ? record.errors : ["Workflow did not produce a result."] }];
}

function workflowRecommendations(record: WorkflowExecutionRecord): string[] {
  return record.result?.recommendations ?? (record.errors.length ? ["Review workflow validation and execution errors."] : ["Workflow completed without recommendations."]);
}

function workflowSummaryItems(workflows: WorkflowSummary[]) {
  return workflows.map((workflow) => `${workflow.name}: ${workflow.status}; trigger ${workflow.triggerType}; state ${workflow.currentState}; last run ${workflow.lastExecutionAt ?? "never"}`);
}

export class CommandRegistry {
  private commands = new Map<string, CommandDefinition>();

  register(command: CommandDefinition) {
    this.commands.set(command.id, command);
    return this;
  }

  list() {
    return Array.from(this.commands.values());
  }

  match(commandText: string) {
    const normalized = normalizeCommand(commandText);
    return this.list().find((command) => [command.label, ...command.aliases].some((alias) => normalizeCommand(alias) === normalized || normalized.includes(normalizeCommand(alias))));
  }

  async execute(context: CommandAgentContext, commandText: string) {
    const match = this.match(commandText);
    if (!match) return this.help(commandText);
    return match.handler(context, commandText);
  }

  help(commandText: string): AgentRunResult {
    const supported = this.list().map((command) => `${command.label} (${command.aliases.join(", ")})`);
    return output("Command help", `I do not recognize “${commandText || "empty command"}”.`, [{ title: "Supported commands", items: supported }], ["Use one of the supported command labels or aliases."], { commandText, matched: false });
  }
}

export function createCommandRegistry() {
  const registry = new CommandRegistry();
  registry
    .register({ id: "platform-health", label: "Show platform health", description: "Show centralized platform health.", category: "observability", permissions: ["dashboard:read"], aliases: ["show platform health", "platform health"], handler: async (context) => { const { getPlatformHealth } = await import("../observability"); const health = await getPlatformHealth({ token: context.accessToken, organizationId: context.organizationId }); return output("Platform Health", `Platform is ${health.status} with ${health.subsystems.length} monitored subsystems.`, [{ title: "Subsystems", items: health.subsystems.map((s) => `${s.label}: ${s.status} — ${s.message}`) }, { title: "Warnings", items: health.warnings }], health.errors.length ? ["Resolve critical health errors before release."] : ["Continue monitoring degraded subsystems."], { matched: true, health }); }})
    .register({ id: "platform-diagnostics", label: "Show diagnostics", description: "Show platform diagnostics.", category: "observability", permissions: ["dashboard:read"], aliases: ["show diagnostics", "diagnostics"], handler: async () => { const { runDiagnostics } = await import("../observability"); const diagnostics = runDiagnostics(); return output("Platform Diagnostics", `${diagnostics.findings.length} diagnostic findings detected.`, [{ title: "Findings", items: diagnostics.findings.map((f) => `${f.severity}: ${f.subsystem}/${f.id} — ${f.message}`) }, { title: "Counts", items: Object.entries(diagnostics.counts).map(([key, value]) => `${key}: ${value}`) }], diagnostics.status === "healthy" ? ["No diagnostic action required."] : ["Review warnings and errors before production release."], { matched: true, diagnostics }); }})
    .register({ id: "degraded-subsystems", label: "Show degraded subsystems", description: "Show degraded platform subsystems.", category: "observability", permissions: ["dashboard:read"], aliases: ["show degraded subsystems", "degraded subsystems"], handler: async (context) => { const { getPlatformHealth } = await import("../observability"); const health = await getPlatformHealth({ token: context.accessToken, organizationId: context.organizationId }); const degraded = health.subsystems.filter((s) => s.status !== "healthy"); return output("Degraded Subsystems", `${degraded.length} subsystems are degraded or unhealthy.`, [{ title: "Subsystems", items: degraded.map((s) => `${s.label}: ${s.status} — ${s.message}`) }], degraded.length ? ["Prioritize unhealthy subsystems first."] : ["All monitored subsystems are healthy."], { matched: true, degraded }); }})
    .register({ id: "startup-checks", label: "Show startup checks", description: "Show startup checks.", category: "observability", permissions: ["dashboard:read"], aliases: ["show startup checks", "startup checks"], handler: async () => { const { runStartupChecks } = await import("../observability"); const findings = runStartupChecks(); return output("Startup Checks", `${findings.length} startup findings detected.`, [{ title: "Findings", items: findings.map((f) => `${f.severity}: ${f.message}`) }], findings.length ? ["Fix startup configuration warnings before production."] : ["Startup checks are clear."], { matched: true, findings }); }})
    .register({ id: "registry-checks", label: "Show registry checks", description: "Show registry checks.", category: "observability", permissions: ["dashboard:read"], aliases: ["show registry checks", "registry checks"], handler: async () => { const { runRegistryChecks } = await import("../observability"); const findings = runRegistryChecks(); return output("Registry Checks", `${findings.length} registry findings detected.`, [{ title: "Findings", items: findings.map((f) => `${f.severity}: ${f.subsystem}/${f.id} — ${f.message}`) }], findings.length ? ["Repair invalid registrations before enabling external connectors."] : ["Registry checks are clear."], { matched: true, findings }); }})
    .register({ id: "runtime-checks", label: "Show runtime checks", description: "Show runtime checks.", category: "observability", permissions: ["runtime:read"], aliases: ["show runtime checks", "runtime checks"], handler: async () => { const { runRuntimeChecks } = await import("../observability"); const findings = runRuntimeChecks(); return output("Runtime Checks", `${findings.length} runtime findings detected.`, [{ title: "Findings", items: findings.map((f) => `${f.severity}: ${f.subsystem}/${f.id} — ${f.message}`) }], findings.length ? ["Review runtime and orchestration health before tool execution."] : ["Runtime checks are clear."], { matched: true, findings }); }})

    .register({ id: "operating-history", label: "Show operating history", description: "Show durable operating history.", category: "history", permissions: ["dashboard:read"], aliases: ["show operating history", "operating history"], handler: async (context) => {
      const history = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }); return output("Operating History", `${history.commands.length} commands, ${history.workflows.length} workflows, and ${history.orchestrationEvents.length} orchestration events are persisted.`, [{ title: "Commands", items: history.commands.map((r) => `${r.status}: ${r.command_text ?? r.correlation_id}`) }, { title: "Workflows", items: history.workflows.map((r) => `${r.status}: ${r.workflow_id}`) }, { title: "Health", items: history.healthSnapshots.map((r) => `${r.status}: ${r.snapshot_type}`) }], [history.commands.length || history.workflows.length ? "Review failed executions before release decisions." : "No durable operating history exists yet."], { matched: true, history });
    }})
    .register({ id: "failed-executions", label: "Show failed executions", description: "Show failed durable execution records.", category: "history", permissions: ["dashboard:read"], aliases: ["show failed executions", "failed executions"], handler: async (context) => { const history = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }); return output("Failed Executions", `${history.failedEvents.length} failed persistent events are visible.`, [{ title: "Failures", items: history.failedEvents.map((r) => `${r.status}: ${r.workflow_id ?? r.agent_id ?? r.correlation_id}`) }], history.failedEvents.length ? ["Inspect error details and replay deterministic work after remediation."] : ["No failed persistent events are visible."], { matched: true, failures: history.failedEvents }); }})
    .register({ id: "recent-commands", label: "Show recent commands", description: "Show recent persisted command executions.", category: "history", permissions: ["dashboard:read"], aliases: ["show recent commands", "recent commands"], handler: async (context) => { const history = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }); return output("Recent Commands", `${history.commands.length} command executions are persisted.`, [{ title: "Commands", items: history.commands.map((r) => `${r.status}: ${r.command_text ?? "command"}`) }], history.commands.length ? ["Use command history to audit executive actions."] : ["No command executions have been persisted yet."], { matched: true, commands: history.commands }); }})
    .register({ id: "recent-workflows", label: "Show recent workflows", description: "Show recent persisted workflow executions.", category: "history", permissions: ["dashboard:read"], aliases: ["show recent workflows", "recent workflows"], handler: async (context) => { const history = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }); return output("Recent Workflows", `${history.workflows.length} workflow executions are persisted.`, [{ title: "Workflows", items: history.workflows.map((r) => `${r.status}: ${r.workflow_id}`) }], history.workflows.length ? ["Use workflow history for deterministic execution audit." ] : ["No workflow executions have been persisted yet."], { matched: true, workflows: history.workflows }); }})
    .register({ id: "recent-orchestration-events", label: "Show recent orchestration events", description: "Show recent persisted orchestration events.", category: "history", permissions: ["agents:read"], aliases: ["show recent orchestration events", "recent orchestration events"], handler: async (context) => { const history = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }); return output("Recent Orchestration Events", `${history.orchestrationEvents.length} orchestration events are persisted.`, [{ title: "Events", items: history.orchestrationEvents.map((r) => `${r.status}: ${r.event_type ?? r.correlation_id}`) }], history.orchestrationEvents.length ? ["Review failed orchestration events before autonomous scheduling."] : ["No orchestration events have been persisted yet."], { matched: true, events: history.orchestrationEvents }); }})
    .register({ id: "recent-health-reports", label: "Show recent health reports", description: "Show recent persisted health snapshots.", category: "history", permissions: ["dashboard:read"], aliases: ["show recent health reports", "recent health reports"], handler: async (context) => { const history = await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }); return output("Recent Health Reports", `${history.healthSnapshots.length} health snapshots are persisted.`, [{ title: "Health snapshots", items: history.healthSnapshots.map((r) => `${r.status}: ${r.snapshot_type}`) }], history.healthSnapshots.length ? ["Trend health snapshots for release readiness." ] : ["No health snapshots have been persisted yet."], { matched: true, health: history.healthSnapshots }); }})
    .register({ id: "priorities", label: "Review today's priorities", description: "Rank urgent work and approvals.", category: "priorities", permissions: ["dashboard:read"], aliases: ["today priorities", "priorities", "review priorities"], handler: (context) => {
      const d = data(context); const recommendations = buildRecommendations({ ...d, organization: d.organizations[0] ?? null, membershipCount: d.memberships.length }); const openTasks = d.tasks.filter(isTaskOpen);
      return output("Today's priorities", `${recommendations.length} recommendations and ${openTasks.length} open tasks are visible.`, [{ title: "Recommendations", items: recommendations.map((r) => `${r.severity}: ${r.title}`) || [] }, { title: "Open tasks", items: openTasks.slice(0, 5).map((task) => task.title) }], recommendations.map((r) => r.action), { matched: true });
    }})
    .register({ id: "attention", label: "What needs my attention?", description: "Show immediate attention queue.", category: "attention", permissions: ["dashboard:read"], aliases: ["attention", "needs attention", "what needs attention"], handler: (context) => {
      const queue = buildAttentionQueue(data(context)); return output("Attention queue", `${queue.length} items need review.`, [{ title: "Items", items: queue.map((item) => `${item.severity}: ${item.title} — ${item.detail}`) }], queue.slice(0, 3).map((item) => `Review ${item.title}.`), { matched: true });
    }})
    .register({ id: "blockers", label: "Show blockers", description: "Summarize blocked and overdue work.", category: "execution", permissions: ["dashboard:read"], aliases: ["blockers", "blocked", "show blocked work"], handler: (context) => {
      const blockers = data(context).tasks.filter((task) => String(task.status ?? "").toLowerCase() === "blocked"); return output("Execution blockers", `${blockers.length} blocked tasks found.`, [{ title: "Blocked tasks", items: blockers.map((task) => task.title) }], blockers.length ? ["Assign owners and next actions to blocked tasks."] : ["No blocked task records are visible."], { matched: true });
    }})
    .register({ id: "activity", label: "Summarize recent activity", description: "Summarize activity and audit logs.", category: "activity", permissions: ["dashboard:read"], aliases: ["activity", "recent activity", "summarize activity"], handler: (context) => {
      const d = data(context); return output("Recent activity", `${d.activity.length} agent activities and ${d.auditLogs.length} audit events are visible.`, [{ title: "Agent activity", items: d.activity.map((item) => item.summary) }, { title: "Audit events", items: d.auditLogs.map((item) => item.action) }], ["Review failed or denied events before release decisions."], { matched: true });
    }})
    .register({ id: "workforce", label: "Review AI workforce", description: "Review agent health.", category: "agents", permissions: ["agents:read"], aliases: ["ai workforce", "agents", "agent health"], handler: (context) => {
      const agents = data(context).agents; const unhealthy = getUnhealthyAgents(agents); return output("AI workforce", `${agents.length} agents registered; ${unhealthy.length} need health review.`, [{ title: "Agents", items: agents.map((agent) => `${agent.name}: ${agent.health ?? agent.status ?? "unknown"}`) }], unhealthy.length ? ["Inspect unhealthy agents before assigning automated workflows."] : ["AI workforce health is clear."], { matched: true });
    }})
    .register({ id: "knowledge-health", label: "Show Knowledge Health", description: "Report Knowledge OS readiness and provider health.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["show knowledge health", "knowledge health", "memory health"], handler: () => {
      const health = buildKnowledgeHealthReport(knowledgeRegistry); return output("Knowledge Health", `Knowledge OS readiness is ${health.readinessScore}% with ${health.indexedDocuments} indexed documents.`, [{ title: "Providers", items: [`${health.providers.memory.length} memory providers`, `${health.providers.search.length} search providers`, `${health.providers.indexing.length} index providers`] }, { title: "Health", items: [`Cache: ${health.cacheHealth}`, `Sync: ${health.synchronizationStatus}`, `Failed indexing jobs: ${health.failedIndexingJobs.length}`] }], ["Connect production providers in future milestones before ingesting organization knowledge."], { matched: true, health });
    }})
    .register({ id: "memory-statistics", label: "Show Memory Statistics", description: "Summarize indexed memory counts.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["show memory statistics", "memory statistics", "memory stats"], handler: () => {
      const providers = knowledgeRegistry.listMemoryProviders(); const total = providers.reduce((sum, provider) => sum + provider.indexedDocumentCount, 0); return output("Memory Statistics", `${total} indexed memory objects across ${providers.length} memory providers.`, [{ title: "Memory providers", items: providers.map((provider) => `${provider.name}: ${provider.indexedDocumentCount} indexed; ${provider.status}`) }], [total ? "Review stale providers before relying on memory freshness." : "No memory objects are indexed yet; empty state is expected before integrations."], { matched: true, providers, total });
    }})
    .register({ id: "list-search-providers", label: "List Search Providers", description: "List registered Knowledge OS search providers.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["list search providers", "search providers"], handler: () => {
      const providers = knowledgeRegistry.listSearchProviders(); return output("Search Providers", `${providers.length} search providers are registered.`, [{ title: "Search providers", items: providers.map((provider) => `${provider.name}: ${provider.status}`) }], ["Keyword, metadata, tag, provider, organization, and permission filtering are supported by the shared interface."], { matched: true, providers });
    }})
    .register({ id: "list-index-providers", label: "List Index Providers", description: "List registered Knowledge OS indexing providers.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["list index providers", "index providers", "indexing providers"], handler: () => {
      const providers = knowledgeRegistry.listIndexingProviders(); return output("Index Providers", `${providers.length} indexing providers are registered.`, [{ title: "Index providers", items: providers.map((provider) => `${provider.name}: ${provider.status}`) }], ["Embeddings are deferred; indexing is deterministic and vector-ready."], { matched: true, providers });
    }})
    .register({ id: "list-memory-providers", label: "List Memory Providers", description: "List registered Knowledge OS memory providers.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["list memory providers", "memory providers", "knowledge sources", "list registered providers"], handler: () => {
      const providers = knowledgeRegistry.listMemoryProviders(); return output("Memory Providers", `${providers.length} memory providers are registered.`, [{ title: "Memory providers", items: providers.map((provider) => `${provider.name}: ${provider.status}; ${provider.indexedDocumentCount} indexed documents; last sync ${provider.lastSyncAt ?? "not synced"}`) }], ["Connect provider integrations in a future milestone before indexing production data."], { matched: true, providers });
    }})
    .register({ id: "search-knowledge", label: "Search Knowledge", description: "Run deterministic Knowledge OS search.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["search knowledge", "knowledge search"], handler: async (context, commandText) => {
      const query = commandText.replace(/search knowledge|knowledge search/ig, "").trim(); const response = await knowledgeRegistry.search({ query, organizationId: context.organizationId, requesterId: context.userId, limit: 5 }); return output("Knowledge Search", `${response.data.length} results for “${query || "all knowledge"}”.`, [{ title: "Results", items: response.data.map((result) => `${result.document.title}: ${result.excerpt}`) }], [response.data.length ? "Open the source provider to inspect the full memory object." : "No indexed knowledge is available yet; connect providers before production search."], { matched: true, query, results: response.data });
    }})
    .register({ id: "indexed-sources", label: "Show Indexed Sources", description: "Show providers with indexed source counts.", category: "knowledge", permissions: ["knowledge:read"], aliases: ["show indexed sources", "indexed sources"], handler: () => {
      const providers = knowledgeRegistry.listMemoryProviders(); return output("Indexed Sources", `${providers.reduce((sum, provider) => sum + provider.indexedDocumentCount, 0)} indexed documents are visible.`, [{ title: "Sources", items: providers.map((provider) => `${provider.name}: ${provider.indexedDocumentCount} indexed`) }], ["No external source has been synchronized in this architecture milestone."], { matched: true, providers });
    }})

    .register({ id: "list-workflows", label: "List workflows", description: "List registered workflow engine definitions.", category: "workflows", permissions: ["dashboard:read"], aliases: ["list workflows", "registered workflows", "show workflows"], handler: () => {
      const workflows = workflowEngine.listWorkflows(); return output("Registered workflows", `${workflows.length} workflows are registered.`, [{ title: "Workflows", items: workflowSummaryItems(workflows) }], ["Execute a workflow by name when deterministic orchestration is needed."], { matched: true, workflows });
    }})
    .register({ id: "workflow-status", label: "Show workflow status", description: "Show workflow execution status and history.", category: "workflows", permissions: ["dashboard:read"], aliases: ["show workflow status", "workflow status", "workflow history"], handler: () => {
      const workflows = workflowEngine.listWorkflows(); const history = workflowEngine.getHistory(); return output("Workflow status", `${workflows.length} workflows tracked with ${history.length} execution records.`, [{ title: "Current status", items: workflowSummaryItems(workflows) }, { title: "Recent executions", items: history.slice(-5).map((record) => `${record.workflowName}: ${record.state} at ${record.completedAt ?? record.startedAt}`) }], ["Use workflow history to audit deterministic agent execution."], { matched: true, workflows, history });
    }})
    .register({ id: "execute-daily-brief-workflow", label: "Execute executive daily brief", description: "Run the Executive Daily Brief workflow.", category: "workflows", permissions: ["dashboard:read"], aliases: ["execute executive daily brief", "run executive daily brief", "daily brief workflow"], handler: async (context) => {
      const record = await workflowEngine.execute("executive-daily-brief", { state: data(context), organizationId: context.organizationId, userId: context.userId, now: context.now, accessToken: context.accessToken }); return output(record.result?.title ?? "Executive Daily Brief", record.result?.summary ?? `Workflow ${record.state}.`, workflowSections(record), workflowRecommendations(record), { matched: true, record });
    }})
    .register({ id: "execute-release-verification-workflow", label: "Execute release verification", description: "Run the Release Verification workflow.", category: "workflows", permissions: ["release:read"], aliases: ["execute release verification", "run release verification", "release verification workflow"], handler: async (context) => {
      const record = await workflowEngine.execute("release-verification", { state: data(context), organizationId: context.organizationId, userId: context.userId, now: context.now, accessToken: context.accessToken }); return output(record.result?.title ?? "Release Verification", record.result?.summary ?? `Workflow ${record.state}.`, workflowSections(record), workflowRecommendations(record), { matched: true, record });
    }})
    .register({ id: "execute-knowledge-discovery-workflow", label: "Execute knowledge discovery", description: "Run the Knowledge Discovery workflow.", category: "workflows", permissions: ["knowledge:read"], aliases: ["execute knowledge discovery", "run knowledge discovery", "knowledge discovery workflow"], handler: async (context) => {
      const record = await workflowEngine.execute("knowledge-discovery", { state: data(context), organizationId: context.organizationId, userId: context.userId, now: context.now, accessToken: context.accessToken }); return output(record.result?.title ?? "Knowledge Discovery", record.result?.summary ?? `Workflow ${record.state}.`, workflowSections(record), workflowRecommendations(record), { matched: true, record });
    }})

    .register({ id: "orchestration-list-agents", label: "List agents", description: "List agents discovered by the orchestration registry.", category: "orchestration", permissions: ["agents:read"], aliases: ["list agents", "show registered agents"], handler: () => {
      const agents = orchestrator.discoverAgents(); return output("Registered agents", `${agents.length} agents are discoverable through orchestration.`, [{ title: "Agents", items: agents.map((agent) => `${agent.name}: ${agent.role}; ${agent.status}/${agent.health}`) }], ["Use delegation commands to enqueue deterministic work for a registered agent."], { matched: true, agents });
    }})
    .register({ id: "orchestration-health", label: "Show orchestration health", description: "Summarize orchestration health and throughput.", category: "orchestration", permissions: ["agents:read"], aliases: ["show orchestration health", "orchestration health"], handler: () => {
      const health = orchestrator.health(); return output("Orchestration health", `Orchestration is ${health.status} with score ${health.healthScore}.`, [{ title: "System", items: [`${health.registeredAgents} registered agents`, `${health.queuedWork} queued tasks`, `${health.completedWork} completed tasks`, `${health.throughputPerMinute} throughput/min`] }], ["Review queued work and failed work before enabling autonomous scheduling."], { matched: true, health });
    }})
    .register({ id: "orchestration-queued-work", label: "Show queued work", description: "Inspect deterministic orchestration queue.", category: "orchestration", permissions: ["agents:read"], aliases: ["show queued work", "queued work", "task queue"], handler: () => {
      const queue = orchestrator.queue.inspect(); return output("Queued work", `${queue.length} orchestration tasks are tracked.`, [{ title: "Tasks", items: queue.map((task) => `${task.id}: ${task.agentId} ${task.status} ${task.priority}`) }], queue.length ? ["Run deterministic dispatch to execute the next queued task."] : ["No queued work is pending."], { matched: true, queue });
    }})
    .register({ id: "orchestration-running-workflows", label: "Show running workflows", description: "Show workflow engine executions visible to orchestration.", category: "orchestration", permissions: ["dashboard:read"], aliases: ["show running workflows", "running workflows"], handler: () => {
      const workflows = workflowEngine.listWorkflows().filter((workflow) => workflow.currentState === "running"); return output("Running workflows", `${workflows.length} workflows are currently running.`, [{ title: "Workflows", items: workflowSummaryItems(workflows) }], workflows.length ? ["Monitor workflow history for completion events."] : ["No workflow is running right now."], { matched: true, workflows });
    }})
    .register({ id: "orchestration-delegate-task", label: "Delegate task", description: "Enqueue deterministic delegated work for an agent.", category: "orchestration", permissions: ["agents:write"], aliases: ["delegate task", "delegate work"], handler: (context, commandText) => {
      const agents = orchestrator.discoverAgents(); const target = agents.find((agent) => commandText.toLowerCase().includes(agent.id.toLowerCase()) || commandText.toLowerCase().includes(agent.name.toLowerCase())) ?? agents[0]; const task = orchestrator.delegate({ toAgentId: target.id, organizationId: context.organizationId, payload: { commandText }, metadata: { delegatedBy: context.userId ?? "executive-command-agent" }, accessToken: context.accessToken, userId: context.userId }); return output("Task delegated", `Queued ${task.id} for ${target.name}.`, [{ title: "Delegation", items: [`Task: ${task.id}`, `Agent: ${target.name}`, `Status: ${task.status}`, `Priority: ${task.priority}`] }], ["Inspect queued work or execution history for the delegation result."], { matched: true, task });
    }})
    .register({ id: "orchestration-execution-history", label: "Show execution history", description: "Show orchestration execution history.", category: "orchestration", permissions: ["agents:read"], aliases: ["show execution history", "execution history"], handler: () => {
      const history = orchestrator.queue.history(); return output("Execution history", `${history.length} orchestration execution records exist.`, [{ title: "Recent executions", items: history.slice(-10).map((record) => `${record.taskId}: ${record.agentId} ${record.status} in ${record.runtimeMs}ms`) }], history.length ? ["Use failed records to tune retry and recovery policy."] : ["No orchestration task has executed yet."], { matched: true, history });
    }})
    .register({ id: "orchestration-agent-metrics", label: "Show agent metrics", description: "Show deterministic agent runtime metrics.", category: "orchestration", permissions: ["agents:read"], aliases: ["show agent metrics", "agent metrics"], handler: () => {
      const metrics = orchestrator.discoverAgents().map((agent) => orchestrator.agentMetrics(agent.id)); return output("Agent metrics", `${metrics.length} agent metric snapshots calculated.`, [{ title: "Metrics", items: metrics.map((metric) => `${metric.agentId}: ${metric.healthScore} health, ${metric.executionCount} executions, ${metric.successRate}% success`) }], ["Use metrics to route future autonomous work to healthy agents."], { matched: true, metrics });
    }})
    .register({ id: "orchestration-throughput", label: "Show system throughput", description: "Show orchestration throughput.", category: "orchestration", permissions: ["agents:read"], aliases: ["show system throughput", "system throughput"], handler: () => {
      const health = orchestrator.health(); return output("System throughput", `${health.throughputPerMinute} completed tasks per deterministic reporting window.`, [{ title: "Throughput", items: [`Completed: ${health.completedWork}`, `Failed: ${health.failedWork}`, `Queued: ${health.queuedWork}`] }], ["Persistent throughput windows can replace in-memory metrics in a future milestone."], { matched: true, health });
    }})
    .register({ id: "runtime-list-tools", label: "List tools", description: "List AI Runtime tools.", category: "runtime", permissions: ["runtime:read"], aliases: ["list tools", "runtime tools"], handler: () => { const tools = aiRuntime.registry.listTools(); return output("Runtime Tools", `${tools.length} tools are registered.`, [{ title: "Tools", items: tools.map((tool) => `${tool.name}: ${tool.category}; ${tool.health}; ${tool.version}`) }], [tools.length ? "Use execute tool with deterministic mock tools only." : "Register runtime tools before execution."], { matched: true, tools }); }})
    .register({ id: "runtime-health", label: "Show runtime health", description: "Show AI Runtime health.", category: "runtime", permissions: ["runtime:read"], aliases: ["show runtime health", "runtime health"], handler: () => { const metrics = aiRuntime.telemetry.metrics(); return output("Runtime Health", `Runtime is ${metrics.runtimeHealth} with ${metrics.successRate}% success.`, [{ title: "Metrics", items: [`Executions: ${metrics.executions}`, `Failures: ${metrics.failures}`, `Average duration: ${metrics.averageDurationMs}ms`, `Policy violations: ${metrics.policyViolations}`] }], [metrics.policyViolations ? "Review denied policy events." : "Runtime policy is clear."], { matched: true, metrics }); }})
    .register({ id: "runtime-sessions", label: "Show runtime sessions", description: "Show AI Runtime sessions.", category: "runtime", permissions: ["runtime:read"], aliases: ["show runtime sessions", "runtime sessions"], handler: () => { const sessions = aiRuntime.executor.sessions; return output("Runtime Sessions", `${sessions.length} runtime sessions are in memory.`, [{ title: "Sessions", items: sessions.slice(-10).map((session) => `${session.id}: ${session.result?.success ? "succeeded" : "failed"} ${session.toolsUsed.join(", ")}`) }], [sessions.length ? "Use session timelines for runtime audit." : "No runtime sessions have executed yet."], { matched: true, sessions }); }})
    .register({ id: "runtime-telemetry", label: "Show runtime telemetry", description: "Show deterministic runtime telemetry.", category: "runtime", permissions: ["runtime:read"], aliases: ["show runtime telemetry", "runtime telemetry"], handler: () => { const metrics = aiRuntime.telemetry.metrics(); return output("Runtime Telemetry", `${metrics.executions} executions with ${metrics.retryCount} retries.`, [{ title: "Tool usage", items: Object.entries(metrics.toolUsage).map(([tool, count]) => `${tool}: ${count}`) }, { title: "Organization usage", items: Object.entries(metrics.organizationUsage).map(([org, count]) => `${org}: ${count}`) }], ["Telemetry is deterministic and in-memory until persistence tables are expanded."], { matched: true, metrics }); }})
    .register({ id: "runtime-policy-violations", label: "Show policy violations", description: "Show runtime policy violations.", category: "runtime", permissions: ["runtime:read"], aliases: ["show policy violations", "policy violations"], handler: () => { const violations = aiRuntime.executor.sessions.flatMap((session) => session.events.filter((event) => event.type === "policy.denied")); return output("Runtime Policy Violations", `${violations.length} policy violations recorded.`, [{ title: "Violations", items: violations.map((event) => `${event.sessionId}: ${event.message}`) }], [violations.length ? "Tighten permissions or tool allowlists before retrying." : "No runtime policy violations are recorded."], { matched: true, violations }); }})
    .register({ id: "runtime-validate", label: "Validate runtime", description: "Validate runtime registry.", category: "runtime", permissions: ["runtime:read"], aliases: ["validate runtime", "runtime validate"], handler: () => { const tools = aiRuntime.registry.listTools(); const unhealthy = tools.filter((tool) => tool.health !== "healthy"); return output("Runtime Validation", `${tools.length} tools validated; ${unhealthy.length} unhealthy.`, [{ title: "Validation", items: tools.map((tool) => `${tool.id}: ${tool.health}; deterministic=${tool.deterministic}`) }], [unhealthy.length ? "Review unhealthy tools." : "Runtime registry is valid."], { matched: true, tools, unhealthy }); }})
    .register({ id: "runtime-execute-tool", label: "Execute tool", description: "Execute deterministic AI Runtime mock tool.", category: "runtime", permissions: ["runtime:execute"], aliases: ["execute tool", "run tool"], handler: async (context, commandText) => { const tool = aiRuntime.registry.listTools().find((candidate) => commandText.toLowerCase().includes(candidate.id.toLowerCase()) || commandText.toLowerCase().includes(candidate.name.toLowerCase())) ?? aiRuntime.registry.getTool("runtime.echo")!; const runtimeContext = createRuntimeContext({ organizationId: context.organizationId, userId: context.userId, agentId: "executive-command-agent", permissions: ["runtime:read", "runtime:execute", "dashboard:read", "knowledge:read"], accessToken: context.accessToken, now: context.now?.toISOString() }); const session = await aiRuntime.executor.execute({ toolId: tool.id, input: tool.id === "runtime.echo" ? { message: commandText } : {}, context: runtimeContext, policy: { requireDeterministic: true, maxRetries: 1, maxTimeoutMs: 5000 } }); return output("Runtime Tool Execution", `Executed ${tool.name} with ${session.result?.success ? "success" : "failure"}.`, [{ title: "Session", items: [`Session: ${session.id}`, `Tool: ${tool.id}`, `Duration: ${session.durationMs ?? 0}ms`] }, { title: "Timeline", items: session.timeline.map((event) => `${event.type}: ${event.message}`) }], session.result?.success ? ["Runtime execution completed deterministically."] : ["Review runtime errors before retrying."], { matched: true, session }); }})
    .register({ id: "connectors-list", label: "List connectors", description: "List enterprise connectors.", category: "connectors", permissions: ["connectors:read"], aliases: ["list connectors", "enterprise connectors"], handler: async () => { const { connectorManager } = await import("../connectors"); const connectors = connectorManager.list(); return output("Enterprise Connectors", `${connectors.length} connectors are registered.`, [{ title: "Connectors", items: connectors.map((connector) => `${connector.name}: ${connector.provider}; ${connector.health.status}; auth ${connector.health.authenticationStatus}`) }], [connectors.length ? "Use connector health, capabilities, diagnostics, or sessions commands for detail." : "Register deterministic connector definitions before execution."], { matched: true, connectors }); }})
    .register({ id: "connectors-health", label: "Show connector health", description: "Show enterprise connector health.", category: "connectors", permissions: ["connectors:read"], aliases: ["show connector health", "connector health"], handler: async () => { const { connectorManager } = await import("../connectors"); const health = connectorManager.health(); return output("Connector Health", `${health.length} connector health records are available.`, [{ title: "Health", items: health.map((item) => `${item.name}: ${item.health.status}; score ${item.health.healthScore}; auth ${item.health.authenticationStatus}`) }], [health.every((item) => item.health.status === "healthy") ? "Connector framework health is clear." : "Review degraded connector diagnostics."], { matched: true, health }); }})
    .register({ id: "connectors-capabilities", label: "Show connector capabilities", description: "Show enterprise connector capabilities.", category: "connectors", permissions: ["connectors:read"], aliases: ["show connector capabilities", "connector capabilities"], handler: async () => { const { connectorManager } = await import("../connectors"); const capabilities = connectorManager.capabilities(); return output("Connector Capabilities", `${capabilities.length} connector capability profiles are available.`, [{ title: "Capabilities", items: capabilities.map((item) => `${item.connectorId}: ${item.capabilities.map((capability) => capability.name).join(", ")}; operations ${item.operations.map((operation) => operation.id).join(", ")}`) }], ["Future production integrations should add capabilities without changing registry routing."], { matched: true, capabilities }); }})
    .register({ id: "connectors-auth", label: "Show authentication status", description: "Show connector authentication status.", category: "connectors", permissions: ["connectors:read"], aliases: ["show authentication status", "connector authentication", "auth status"], handler: async () => { const { connectorManager } = await import("../connectors"); const connectors = connectorManager.list(); return output("Connector Authentication", `${connectors.length} connector authentication records are visible.`, [{ title: "Authentication", items: connectors.map((connector) => `${connector.name}: ${connector.health.authenticationStatus}; strategies ${connector.authentication.strategies.join(", ")}`) }], ["OAuth and secret material are intentionally not implemented in this deterministic milestone."], { matched: true, connectors }); }})
    .register({ id: "connectors-diagnostics", label: "Show connector diagnostics", description: "Show connector diagnostics.", category: "connectors", permissions: ["connectors:read"], aliases: ["show connector diagnostics", "connector diagnostics"], handler: async () => { const { connectorManager } = await import("../connectors"); const diagnostics = connectorManager.diagnostics(); return output("Connector Diagnostics", `${diagnostics.connectors.length} connector diagnostic records; ${diagnostics.telemetry.events} events.`, [{ title: "Diagnostics", items: diagnostics.connectors.map((item) => `${item.id}: ${item.diagnostics.join(" ") || "No diagnostics"}`) }, { title: "Telemetry", items: Object.entries(diagnostics.telemetry).filter(([key]) => key !== "recentEvents").map(([key, value]) => `${key}: ${value}`) }], ["Use diagnostics before enabling production connector implementations."], { matched: true, diagnostics }); }})
    .register({ id: "connectors-sessions", label: "Show connector sessions", description: "Show connector runtime sessions.", category: "connectors", permissions: ["connectors:read"], aliases: ["show connector sessions", "connector sessions"], handler: async () => { const { connectorManager } = await import("../connectors"); const sessions = connectorManager.runtime.sessions; return output("Connector Sessions", `${sessions.length} connector sessions are tracked.`, [{ title: "Sessions", items: sessions.slice(-10).map((session) => `${session.id}: ${session.connectorId}; executions ${session.executions.length}`) }], [sessions.length ? "Review session correlation IDs for audit." : "No connector sessions have executed yet."], { matched: true, sessions }); }})
    .register({ id: "connectors-validate", label: "Validate connectors", description: "Validate registered connectors.", category: "connectors", permissions: ["connectors:read"], aliases: ["validate connectors", "connector validation"], handler: async () => { const { connectorManager } = await import("../connectors"); const validations = connectorManager.list().map((connector) => ({ id: connector.id, ...connectorManager.registry.validateConnector(connector.id) })); return output("Connector Validation", `${validations.length} connectors validated.`, [{ title: "Validation", items: validations.map((validation) => `${validation.id}: ${validation.valid ? "valid" : validation.errors.join("; ")}`) }], [validations.every((validation) => validation.valid) ? "All connector definitions are valid." : "Repair invalid connector definitions before production."], { matched: true, validations }); }})
    .register({ id: "executive-intelligence-briefing", label: "Executive briefing", description: "Show deterministic executive intelligence briefing.", category: "executive", permissions: ["dashboard:read"], aliases: ["executive briefing", "executive intelligence", "briefing"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Executive briefing", snapshot.trendSummary, [{ title: "Top priorities", items: snapshot.priorities.map((p) => `${p.rank}. ${p.title} — ${p.recommendedNextStep}`) }, { title: "Executive score", items: [`Overall: ${snapshot.score.overall}`, ...snapshot.score.categories.map((c) => `${c.category}: ${c.score}`)] }], snapshot.recommendations.map((r) => r.suggestedAction), { matched: true, snapshot }); }})
    .register({ id: "executive-score", label: "Executive score", description: "Explain executive health score.", category: "executive", permissions: ["dashboard:read"], aliases: ["executive score", "explain executive score"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Executive score", `${snapshot.score.overall}/100 confidence ${snapshot.score.confidence}.`, [{ title: "Categories", items: snapshot.score.categories.map((c) => `${c.category}: ${c.score} — ${c.explanation}`) }], [explainExecutiveScore(snapshot)], { matched: true, score: snapshot.score }); }})
    .register({ id: "executive-priorities", label: "Top priorities", description: "Show ranked executive priorities.", category: "executive", permissions: ["dashboard:read"], aliases: ["top priorities", "strategic priorities"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Top priorities", `${snapshot.priorities.length} priorities ranked.`, [{ title: "Priorities", items: snapshot.priorities.map((p) => `${p.rank}. ${p.severity}: ${p.title}`) }], snapshot.priorities.map((p) => p.recommendedNextStep), { matched: true, priorities: snapshot.priorities }); }})
    .register({ id: "executive-risks", label: "Strategic risks", description: "Show ranked executive risks.", category: "executive", permissions: ["dashboard:read"], aliases: ["strategic risks", "risks"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Strategic risks", `${snapshot.risks.length} risks detected.`, [{ title: "Risks", items: snapshot.risks.map((r) => `${r.rank}. ${r.severity}: ${r.title} — ${r.mitigation}`) }], snapshot.risks.map((r) => r.mitigation), { matched: true, risks: snapshot.risks }); }})
    .register({ id: "executive-opportunities", label: "Opportunities", description: "Show executive opportunities.", category: "executive", permissions: ["dashboard:read"], aliases: ["opportunities", "strategic opportunities"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Opportunities", `${snapshot.opportunities.length} opportunities detected.`, [{ title: "Opportunities", items: snapshot.opportunities.map((o) => `${o.leverage}: ${o.title} — ${o.suggestedExperiment}`) }], snapshot.opportunities.map((o) => o.suggestedExperiment), { matched: true, opportunities: snapshot.opportunities }); }})
    .register({ id: "executive-bottlenecks", label: "Bottlenecks", description: "Show executive bottlenecks.", category: "executive", permissions: ["dashboard:read"], aliases: ["bottlenecks", "constraints"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Bottlenecks", `${snapshot.bottlenecks.length} bottlenecks detected.`, [{ title: "Bottlenecks", items: snapshot.bottlenecks.map((b) => `${b.severity}: ${b.title} — ${b.reliefAction}`) }], snapshot.bottlenecks.map((b) => b.reliefAction), { matched: true, bottlenecks: snapshot.bottlenecks }); }})
    .register({ id: "executive-recommendations", label: "Recommendations", description: "Show executive recommendations.", category: "executive", permissions: ["dashboard:read"], aliases: ["recommendations", "executive recommendations"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Recommendations", `${snapshot.recommendations.length} recommendations generated.`, [{ title: "Recommendations", items: snapshot.recommendations.map((r) => `${r.severity}: ${r.title} — ${r.suggestedAction}`) }], snapshot.recommendations.map((r) => r.suggestedAction), { matched: true, recommendations: snapshot.recommendations }); }})
    .register({ id: "executive-timeline", label: "Executive timeline", description: "Show executive intelligence timeline.", category: "executive", permissions: ["dashboard:read"], aliases: ["executive timeline", "timeline"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Executive timeline", `${snapshot.timeline.length} timeline events generated.`, [{ title: "Timeline", items: snapshot.timeline.map((e) => `${e.at}: ${e.severity} ${e.title}`) }], ["Use timeline events to review deterministic operating changes."], { matched: true, timeline: snapshot.timeline }); }})
    .register({ id: "why-important", label: "Why is this important?", description: "Explain why executive intelligence matters.", category: "executive", permissions: ["dashboard:read"], aliases: ["why is this important", "why important"], handler: async (context) => { const snapshot = await executiveSnapshotFor(context); return output("Why this is important", "Executive Intelligence turns subsystem telemetry into deterministic operating decisions without making an LLM the source of truth.", [{ title: "Importance", items: [snapshot.trendSummary, "Priorities, risks, opportunities, bottlenecks, and recommendations are structured and auditable."] }], snapshot.priorities.map((p) => p.recommendedNextStep), { matched: true }); }})
    .register({ id: "autonomous-plans", label: "Show autonomous plans", description: "Show deterministic autonomous plans.", category: "autonomy", permissions: ["dashboard:read"], aliases: ["show autonomous plans", "autonomous plans"], handler: async (context) => { const { autonomyEngine } = await import("../autonomy"); const snapshot = await executiveSnapshotFor(context); const d = data(context); const plan = autonomyEngine.createExecutionPlan({ organization: d.organizations[0] ? { id: d.organizations[0].id, name: d.organizations[0].name } : null, executiveIntelligence: snapshot, workflows: workflowEngine.listWorkflows(), runtimeTools: aiRuntime.registry.listTools(), connectors: connectorManager.list(), platformHealth: await (await import("../observability")).getPlatformHealth({ token: context.accessToken, organizationId: context.organizationId }), operatingHistory: await getOperatingHistory({ token: context.accessToken, organizationId: context.organizationId, profileId: context.userId }), source: "command" }); return output("Autonomous Plans", `${autonomyEngine.listPlans().length} autonomous plans available.`, [{ title: "Plans", items: autonomyEngine.listPlans().map((p) => `${p.id}: ${p.status}; ${p.tasks.length} tasks`) }], ["Review required approvals before scheduling live execution."], { matched: true, plan }); }})
    .register({ id: "autonomous-pending-approvals", label: "Show pending approvals", description: "Show autonomous pending approvals.", category: "autonomy", permissions: ["approvals:read"], aliases: ["show pending approvals", "pending approvals"], handler: async () => { const { approvalEngine } = await import("../autonomy"); const approvals = approvalEngine.list("pending"); return output("Pending Approvals", `${approvals.length} autonomous approvals are pending.`, [{ title: "Approvals", items: approvals.map((a) => `${a.id}: ${a.level} for ${a.taskId}`) }], [approvals.length ? "Approve, reject, defer, or expire approvals explicitly." : "No autonomous approvals are pending."], { matched: true, approvals }); }})
    .register({ id: "autonomous-approve", label: "Approve plan", description: "Approve the first pending autonomous approval deterministically.", category: "autonomy", permissions: ["approvals:write"], aliases: ["approve plan"], handler: async (context) => { const { approvalEngine } = await import("../autonomy"); const pending = approvalEngine.list("pending")[0]; if (!pending) return output("Approve Plan", "No pending autonomous approval found.", [{ title: "Result", items: ["No approval changed."] }], ["Create a plan first."], { matched: true }); const approval = approvalEngine.approve(pending.id, context.userId ?? "executive", "Approved by executive command.", [], pending.requiredParties[0]); return output("Approve Plan", `${approval.id} is ${approval.status}.`, [{ title: "Approval", items: [`${approval.level}: ${approval.reason}`] }], ["Continue collecting approvals until plan is approved."], { matched: true, approval }); }})
    .register({ id: "autonomous-reject", label: "Reject plan", description: "Reject the first pending autonomous approval deterministically.", category: "autonomy", permissions: ["approvals:write"], aliases: ["reject plan"], handler: async (context) => { const { approvalEngine } = await import("../autonomy"); const pending = approvalEngine.list("pending")[0]; if (!pending) return output("Reject Plan", "No pending autonomous approval found.", [{ title: "Result", items: ["No approval changed."] }], ["Create a plan first."], { matched: true }); const approval = approvalEngine.reject(pending.id, context.userId ?? "executive", "Rejected by executive command."); return output("Reject Plan", `${approval.id} rejected.`, [{ title: "Approval", items: [approval.reason] }], ["Revise the execution plan before requesting approval again."], { matched: true, approval }); }})
    .register({ id: "autonomous-pause", label: "Pause execution", description: "Pause autonomous execution simulation.", category: "autonomy", permissions: ["runtime:execute"], aliases: ["pause execution"], handler: async () => output("Pause Execution", "Autonomous execution pause requested; live execution is disabled.", [{ title: "Boundary", items: ["No live autonomous execution is running."] }], ["Use resume only after policy review."], { matched: true }) })
    .register({ id: "autonomous-resume", label: "Resume execution", description: "Resume autonomous execution simulation.", category: "autonomy", permissions: ["runtime:execute"], aliases: ["resume execution"], handler: async () => output("Resume Execution", "Autonomous execution resume requested for simulation only.", [{ title: "Boundary", items: ["Live execution remains disabled."] }], ["Schedule deterministic simulation first."], { matched: true }) })
    .register({ id: "autonomous-retry-queue", label: "Show retry queue", description: "Show autonomous retry queue.", category: "autonomy", permissions: ["dashboard:read"], aliases: ["show retry queue", "retry queue"], handler: async () => { const { retryEngine } = await import("../autonomy"); const queue = retryEngine.list(); return output("Retry Queue", `${queue.length} retry records.`, [{ title: "Retries", items: queue.map((r) => `${r.taskId}: ${r.classification} attempt ${r.attempt}`) }], [queue.length ? "Investigate exhausted retries." : "Retry queue is empty."], { matched: true, queue }); }})
    .register({ id: "autonomous-recovery-queue", label: "Show recovery queue", description: "Show autonomous recovery queue.", category: "autonomy", permissions: ["dashboard:read"], aliases: ["show recovery queue", "recovery queue"], handler: async () => { const { recoveryEngine } = await import("../autonomy"); const queue = recoveryEngine.list(); return output("Recovery Queue", `${queue.length} recovery plans.`, [{ title: "Recovery", items: queue.map((r) => `${r.taskId}: ${r.rollbackRequirement}`) }], [queue.length ? "Complete recovery before retrying." : "Recovery queue is empty."], { matched: true, queue }); }})
    .register({ id: "autonomous-explain-plan", label: "Explain execution plan", description: "Explain deterministic autonomous plan structure.", category: "autonomy", permissions: ["dashboard:read"], aliases: ["explain execution plan"], handler: async () => { const { autonomyEngine } = await import("../autonomy"); const plan = autonomyEngine.listPlans()[0]; return output("Explain Execution Plan", plan ? `${plan.tasks.length} tasks ordered by deterministic dependencies.` : "No plan exists.", [{ title: "Explanation", items: plan ? plan.tasks.map((t) => `${t.id}: ${t.approvalLevel}, rollback ${t.rollbackRequirement}`) : ["Create a plan first."] }], ["Approval levels are policy-derived, not generated text."], { matched: true, plan }); }})
    .register({ id: "autonomous-explain-approval", label: "Explain approval decision", description: "Explain deterministic approval policy.", category: "autonomy", permissions: ["approvals:read"], aliases: ["explain approval decision"], handler: async () => { const { approvalEngine } = await import("../autonomy"); const approval = approvalEngine.list()[0]; return output("Explain Approval Decision", approval ? approval.reason : "No approval exists.", [{ title: "Policy Evidence", items: approval ? approval.evidence.map((e) => `${e.label}: ${e.value}`) : ["Create a plan first."] }], ["Approval decisions include approver, timestamp, reason, expiration, and evidence."], { matched: true, approval }); }})
    .register({ id: "github-status", label: "GitHub status", description: "Show GitHub connector status through Connector Runtime.", category: "github", permissions: ["connectors:read"], aliases: ["github status", "explain github health"], handler: async (context) => { const { connectorManager, githubTelemetrySummary } = await import("../connectors"); const github = connectorManager.list().find((c) => c.id === "github"); return output("GitHub Status", github ? `GitHub is ${github.health.status}; auth ${github.health.authenticationStatus}.` : "GitHub connector is not registered.", [{ title: "Health", items: github ? [`score ${github.health.healthScore}`, ...github.health.diagnostics] : ["Missing connector"] }, { title: "Telemetry", items: Object.entries(githubTelemetrySummary()).filter(([k]) => k !== "recent").map(([k,v]) => `${k}: ${JSON.stringify(v)}`) }], [github?.health.authenticationStatus === "authenticated" ? "Run repository and workflow commands for live detail." : "Configure GitHub credentials before live operations."], { matched: true, github }); }})
    .register({ id: "github-repositories", label: "GitHub repositories", description: "List GitHub repositories through Connector Runtime.", category: "github", permissions: ["connectors:read"], aliases: ["github repositories", "review repository"], handler: async (context) => { const { connectorRuntime } = await import("../connectors"); const result = await connectorRuntime.execute({ connectorId: "github", operationId: "repos.list", input: { organization: context.organizationId, per_page: 10 }, context: { organizationId: context.organizationId, userId: context.userId, runtimeSessionId: `cmd-${context.now instanceof Date ? context.now.toISOString() : String(context.now)}`, correlationId: `github-repos-${Date.now()}`, permissions: [], now: context.now instanceof Date ? context.now.toISOString() : String(context.now) } }); return output("GitHub Repositories", result.success ? "Repository listing completed through Connector Runtime." : `Repository listing failed: ${result.error?.message}`, [{ title: "Result", items: [result.success ? "Live repository data returned in metadata." : result.error?.code ?? "unknown"] }], [result.success ? "Review repositories requiring attention." : "Verify GitHub auth and organization input."], { matched: true, result }); }})
    .register({ id: "github-pull-requests", label: "GitHub pull requests", description: "List GitHub pull requests through Connector Runtime.", category: "github", permissions: ["connectors:read"], aliases: ["github pull requests", "github prs", "pr waiting for review"], handler: async (context) => output("GitHub Pull Requests", "Provide owner/repo context in workflow automation to list pull requests through Connector Runtime.", [{ title: "Runtime", items: ["Operation: pulls.list", "Approval: automatic read-only"] }], ["Use a repository-scoped automation request for live PR data."], { matched: true }) })
    .register({ id: "github-workflow-failures", label: "GitHub workflow failures", description: "Show workflow failure operation routing.", category: "github", permissions: ["connectors:read"], aliases: ["github workflow failures", "github deployments", "github engineering health"], handler: async () => output("GitHub Engineering Health", "GitHub workflow, deployment, and engineering-health commands are routed through the GitHub connector runtime operations.", [{ title: "Operations", items: ["actions.runs", "actions.failed_jobs", "deployments.list", "engineering.health", "rate_limit.read"] }], ["Review failed workflows, stale PRs, and deployment failures before release decisions."], { matched: true }) })
    .register({ id: "github-rate-limit", label: "GitHub rate limit", description: "Show GitHub rate limit telemetry.", category: "github", permissions: ["connectors:read"], aliases: ["github rate limit"], handler: async () => { const { githubTelemetrySummary } = await import("../connectors"); const telemetry = githubTelemetrySummary(); return output("GitHub Rate Limit", "Most recent GitHub rate-limit data is recorded in telemetry after live requests.", [{ title: "Telemetry", items: Object.entries(telemetry).filter(([k]) => k !== "recent").map(([k,v]) => `${k}: ${JSON.stringify(v)}`) }], ["Run a live GitHub operation to refresh rate-limit headers."], { matched: true, telemetry }); }})

    .register({ id: "workspace-readiness", label: "Workspace readiness", description: "Show Google Workspace readiness through Connector Runtime.", category: "workspace", permissions: ["connectors:read"], aliases: ["workspace readiness", "explain workspace health"], handler: async (context) => { const { connectorRuntime, googleWorkspaceTelemetrySummary } = await import("../connectors"); const services = [{id:"gmail",op:"intelligence.summary"},{id:"google-calendar",op:"intelligence.summary"},{id:"google-drive",op:"intelligence.summary"},{id:"google-docs",op:"documents.list"},{id:"google-sheets",op:"intelligence.summary"}]; const results = await Promise.all(services.map((s) => connectorRuntime.execute({ connectorId: s.id, operationId: s.op, context: { organizationId: context.organizationId, userId: context.userId, workflowId: "command-agent", runtimeSessionId: `workspace-${Date.now()}`, correlationId: `${s.id}-${Date.now()}`, permissions: [], now: context.now instanceof Date ? context.now.toISOString() : String(context.now), metadata: { approvalContext: { command: "workspace-readiness" } } } }))); const scores = results.map((r) => Number((r.output?.snapshot as { readinessScore?: number } | undefined)?.readinessScore ?? 0)); const avg = Math.round(scores.reduce((a,b)=>a+b,0)/Math.max(scores.length,1)); return output("Workspace Readiness", `Google Workspace readiness score is ${avg}.`, [{ title: "Providers", items: results.map((r) => `${r.connectorId}: ${r.success ? "ready" : r.error?.message}`) }, { title: "Telemetry", items: Object.entries(googleWorkspaceTelemetrySummary()).filter(([k]) => k !== "recent").map(([k,v]) => `${k}: ${JSON.stringify(v)}`) }], [avg >= 80 ? "Workspace is operationally ready." : "Review provider recommendations before autonomous execution."], { matched: true, results, readinessScore: avg }); }})
    .register({ id: "gmail-status", label: "Gmail status", description: "Show Gmail inbox health.", category: "workspace", permissions: ["connectors:read"], aliases: ["gmail status", "inbox summary"], handler: async (context) => { const { connectorRuntime } = await import("../connectors"); const result = await connectorRuntime.execute({ connectorId: "gmail", operationId: "intelligence.summary", context: { organizationId: context.organizationId, userId: context.userId, workflowId: "command-agent", runtimeSessionId: `gmail-${Date.now()}`, correlationId: `gmail-${Date.now()}`, permissions: [], now: context.now instanceof Date ? context.now.toISOString() : String(context.now) } }); const snapshot = result.output?.snapshot as { counters?: Record<string, number>; recommendations?: string[] } | undefined; return output("Gmail Status", result.success ? "Gmail inbox summary completed through Connector Runtime." : `Gmail failed: ${result.error?.message}`, [{ title: "Inbox", items: Object.entries(snapshot?.counters ?? {}).map(([k,v]) => `${k}: ${v}`) }], snapshot?.recommendations ?? ["Configure Gmail credentials."], { matched: true, result }); }})
    .register({ id: "calendar-conflicts", label: "Calendar conflicts", description: "Show Google Calendar conflicts.", category: "workspace", permissions: ["connectors:read"], aliases: ["calendar today", "calendar conflicts"], handler: async (context) => { const { connectorRuntime } = await import("../connectors"); const result = await connectorRuntime.execute({ connectorId: "google-calendar", operationId: "intelligence.summary", context: { organizationId: context.organizationId, userId: context.userId, workflowId: "command-agent", runtimeSessionId: `calendar-${Date.now()}`, correlationId: `calendar-${Date.now()}`, permissions: [], now: context.now instanceof Date ? context.now.toISOString() : String(context.now) } }); const snapshot = result.output?.snapshot as { counters?: Record<string, number>; recommendations?: string[] } | undefined; return output("Calendar Conflicts", result.success ? "Calendar summary completed through Connector Runtime." : `Calendar failed: ${result.error?.message}`, [{ title: "Calendar", items: Object.entries(snapshot?.counters ?? {}).map(([k,v]) => `${k}: ${v}`) }], snapshot?.recommendations ?? ["Configure Calendar credentials."], { matched: true, result }); }})
    .register({ id: "drive-health", label: "Drive health", description: "Show Google Drive health and search routing.", category: "workspace", permissions: ["connectors:read"], aliases: ["drive health", "drive search"], handler: async (context) => { const { connectorRuntime } = await import("../connectors"); const result = await connectorRuntime.execute({ connectorId: "google-drive", operationId: "intelligence.summary", context: { organizationId: context.organizationId, userId: context.userId, workflowId: "command-agent", runtimeSessionId: `drive-${Date.now()}`, correlationId: `drive-${Date.now()}`, permissions: [], now: context.now instanceof Date ? context.now.toISOString() : String(context.now) } }); const snapshot = result.output?.snapshot as { counters?: Record<string, number>; recommendations?: string[] } | undefined; return output("Drive Health", result.success ? "Drive health completed through Connector Runtime." : `Drive failed: ${result.error?.message}`, [{ title: "Drive", items: Object.entries(snapshot?.counters ?? {}).map(([k,v]) => `${k}: ${v}`) }], snapshot?.recommendations ?? ["Configure Drive credentials."], { matched: true, result }); }})
    .register({ id: "docs-sheets-status", label: "Docs status", description: "Show Docs and Sheets status.", category: "workspace", permissions: ["connectors:read"], aliases: ["docs status", "sheets status"], handler: async (context) => { const { connectorRuntime } = await import("../connectors"); const mk = (id: string, op: string) => connectorRuntime.execute({ connectorId: id, operationId: op, context: { organizationId: context.organizationId, userId: context.userId, workflowId: "command-agent", runtimeSessionId: `${id}-${Date.now()}`, correlationId: `${id}-${Date.now()}`, permissions: [], now: context.now instanceof Date ? context.now.toISOString() : String(context.now) } }); const results = await Promise.all([mk("google-docs","documents.list"), mk("google-sheets","intelligence.summary")]); return output("Docs and Sheets Status", "Docs and Sheets status completed through Connector Runtime.", [{ title: "Results", items: results.map((r) => `${r.connectorId}: ${r.success ? "ready" : r.error?.message}`) }], ["Review stale reports and draft documents."], { matched: true, results }); }})
    .register({ id: "brief", label: "Prepare executive brief", description: "Prepare release and operating summary.", category: "executive", permissions: ["dashboard:read", "release:read"], aliases: ["executive brief", "brief", "prepare brief"], handler: (context) => {
      const d = data(context); const release = evaluateReleaseHealth({ lintPassed: true, typecheckPassed: true, buildPassed: true, criticalBlockers: buildAttentionQueue(d).filter((item) => item.severity === "critical").length, openApprovals: getPendingApprovals(d.approvals).length }); return output("Executive brief", `Release health is ${release.status} with score ${release.score}.`, [{ title: "Release health", items: release.reasons }, { title: "Operating snapshot", items: [`${d.tasks.length} tasks`, `${d.approvals.length} approvals`, `${d.agents.length} agents`] }], release.status === "ready" ? ["Ready for browser preview."] : ["Resolve release health risks before preview."], { matched: true, release });
    }});
  return registry;
}

export const commandRegistry = createCommandRegistry();
