export type VaultIngestionStatus = "available" | "demo_fallback" | "unavailable";
export type VaultRiskFlag = "sensitive_category" | "oversized_file" | "duplicate_candidate" | "cache_volume" | "human_review_required" | "read_only_enforced";

export type VaultSource = { id: string; name: string; databasePath: string; mountedVolume: string; status: VaultIngestionStatus; totalFiles: number; totalSizeBytes: number; lastInventoryTime: string; readOnly: true; safety: VaultGovernanceControls };
export type VaultFileRecord = { id: string; path: string; name: string; folder: string; extension: string; sizeBytes: number; category: string; modifiedAt?: string; riskFlags: VaultRiskFlag[] };
export type VaultCategorySummary = { category: string; workspace: string; fileCount: number; sizeBytes: number; requiresReview: boolean; sensitive: boolean };
export type VaultExtensionSummary = { extension: string; fileCount: number; sizeBytes: number; kind: "document" | "image" | "audio" | "video" | "developer" | "archive" | "installer" | "virtual_machine" | "other" };
export type VaultStorageInsight = { id: string; title: string; description: string; severity: "info" | "review" | "warning"; fileCount?: number; sizeBytes?: number; category?: string; recommendationOnly: true; requiresHumanApproval: true; executionSupported: false };
export type VaultCleanupRecommendation = { id: string; action: string; rationale: string; affectedScope: string; riskFlags: VaultRiskFlag[]; recommendationOnly: true; requiresHumanApproval: true; executionSupported: false };
export type VaultGraphNode = { id: string; type: "vault_source" | "category" | "folder" | "file" | "workspace" | "business" | "case_area" | "media_asset"; label: string; metadata: Record<string, string | number | boolean> };
export type VaultGraphEdge = { from: string; to: string; type: "contains" | "belongs_to" | "mapped_to" | "related_to" | "requires_review" | "potential_duplicate_of" };
export type VaultGovernanceControls = { noFileDeletion: true; noFileMovement: true; noRenaming: true; noFilesystemWrites: true; noAutomaticUploads: true; noContentIndexing: true; noInventoryDatabaseEdits: true; recommendationOnly: true; requiresHumanApproval: true; executionSupported: false };
export type VaultDigitalArchivistReport = { source: VaultSource; categories: VaultCategorySummary[]; extensions: VaultExtensionSummary[]; largestFiles: VaultFileRecord[]; largestFolders: Array<{ folder: string; sizeBytes: number; fileCount: number }>; highVolumeCacheFolders: VaultStorageInsight[]; likelySystemDeveloperFiles: VaultStorageInsight[]; likelyMediaArchives: VaultStorageInsight[]; legalImmigrationConcentration: VaultStorageInsight; fundingConcentration: VaultStorageInsight; businessConcentration: VaultStorageInsight; cleanupRecommendations: VaultCleanupRecommendation[]; archiveRecommendations: VaultCleanupRecommendation[]; sensitiveDataWarnings: VaultStorageInsight[]; nextSafeActions: string[]; graph: { nodes: VaultGraphNode[]; edges: VaultGraphEdge[] } };
export type InventoryProviderSnapshot = { source: VaultSource; categories: VaultCategorySummary[]; extensions: VaultExtensionSummary[]; largestFiles: VaultFileRecord[]; largestFolders: Array<{ folder: string; sizeBytes: number; fileCount: number }>; repeatedFilenames: Array<{ name: string; count: number; totalSizeBytes: number }>; mediaCounts: { images: number; audio: number; video: number }; likelyDuplicates: VaultStorageInsight[]; sensitiveCategories: VaultCategorySummary[] };
export type LocalInventoryProvider = { sourceName: string; databasePath: string; loadSnapshot(): Promise<InventoryProviderSnapshot> };
