import { revalidatePath } from "next/cache";
import { requireActiveOrganization, organizationFilter } from "../../lib/activeOrganization";
import { formBool, formValue, getRows, supabaseRequest } from "../../lib/supabase/data";
import { requireSession } from "../../lib/supabase/server";

export default async function AgentsPage() {
  const { session, activeOrganization } = await requireActiveOrganization();
  async function createAgent(fd: FormData) { "use server"; const s = requireSession(); await supabaseRequest("agent_registry", { token: s.access_token, method: "POST", body: { name: formValue(fd, "name"), role: formValue(fd, "role"), organization_id: formValue(fd, "organization_id"), description: formValue(fd, "description"), prompt: formValue(fd, "prompt"), tools: (formValue(fd, "tools") ?? "").split(",").map((x) => x.trim()).filter(Boolean), permissions: (formValue(fd, "permissions") ?? "").split(",").map((x) => x.trim()).filter(Boolean), approval_required: formBool(fd, "approval_required"), memory_enabled: formBool(fd, "memory_enabled"), status: formValue(fd, "status") ?? "draft", version: formValue(fd, "version") ?? "1.0.0", health: formValue(fd, "health") ?? "Healthy" } }); revalidatePath("/agents"); }
  const agents = await getRows<Record<string, any>>("agent_registry", session.access_token, `?select=*&${organizationFilter(activeOrganization?.id)}&order=name`);
  return <main className="shell"><section className="pageHeader panel"><p className="eyebrow">AI Workforce Registry · {activeOrganization?.name ?? "No active organization"}</p><h1>AI Agents</h1></section><form action={createAgent} className="panel crudForm"><input type="hidden" name="organization_id" value={activeOrganization?.id ?? ""} />{["name", "role", "description", "prompt", "tools", "permissions", "status", "version", "health"].map((f) => <label key={f}>{f.replaceAll("_", " ")}<input name={f} /></label>)}<label className="check"><input type="checkbox" name="approval_required" /> Approval required</label><label className="check"><input type="checkbox" name="memory_enabled" /> Memory enabled</label><button className="button primary">Create agent</button></form><section className="recordGrid">{agents.map((a) => <article className="panel recordCard" key={a.id}><h2>{a.name}</h2><p>{a.role} · {a.status} · {a.health} · v{a.version}</p></article>)}</section></main>;
}
