import { connectorError } from "../../../connector-errors";
import type { ConnectorExecutionRequest, ConnectorExecutionResult } from "../../../connector-types";
import { readiness } from "../shared/intelligence";
import { persistGoogleWorkspaceSnapshot } from "../shared/persistence";
import { recordGoogleWorkspaceTelemetry } from "../shared/telemetry";
import { requireWorkspaceEnvelope } from "../shared/types";
import { evaluateDocsPolicy } from "./policy";
import { validateDocsRequest } from "./validator";
const sampleCounters: Record<string, number> = {"recent":9,"shared":6,"drafts":2,"comments":4};
export async function executeDocsOperation(request: ConnectorExecutionRequest): Promise<ConnectorExecutionResult> { const started=Date.now(); const validation=validateDocsRequest(request); if(!validation.valid) return { connectorId:'google-docs', operationId:request.operationId, success:false, error:connectorError('GOOGLE_WORKSPACE_CONTEXT_INVALID', validation.errors.join(' ')), durationMs:Date.now()-started, correlationId:request.context.correlationId }; const approved = request.input?.approved === true || request.context.metadata?.approved === true; const policy=evaluateDocsPolicy(request.operationId, approved); if(!policy.allowed){ recordGoogleWorkspaceTelemetry({service:'docs', operationId:request.operationId, status:'denied', durationMs:Date.now()-started, correlationId:request.context.correlationId, at:new Date().toISOString()}); return { connectorId:'google-docs', operationId:request.operationId, success:false, error:connectorError('APPROVAL_REQUIRED', policy.reason), durationMs:Date.now()-started, correlationId:request.context.correlationId }; } const envelope=requireWorkspaceEnvelope(request.context,'google-docs',request.operationId); const snapshot=persistGoogleWorkspaceSnapshot(readiness('docs', sampleCounters)); const durationMs=Date.now()-started; recordGoogleWorkspaceTelemetry({service:'docs', operationId:request.operationId, status:'success', durationMs, correlationId:request.context.correlationId, at:new Date().toISOString(), details:{readinessScore:snapshot.readinessScore}}); return { connectorId:'google-docs', operationId:request.operationId, success:true, output:{ service:'docs', operation:request.operationId, envelope, snapshot, approval:policy, deterministicIntelligence:true, networkCalls:0 }, durationMs, correlationId:request.context.correlationId }; }
