import type { ApprovalDecision, ExecutionPlan, RecoveryPlan, RetryRecord, ScheduledPlan } from "../../lib/autonomy";

type Props = { plans: ExecutionPlan[]; approvals: ApprovalDecision[]; schedules: ScheduledPlan[]; retryQueue: RetryRecord[]; recoveryQueue: RecoveryPlan[] };
const empty = "No deterministic records yet.";
export function AutonomousOperationsPanel({ plans, approvals, schedules, retryQueue, recoveryQueue }: Props) {
  const pending = approvals.filter((approval) => approval.status === "pending");
  const active = plans.filter((plan) => ["approved", "scheduled", "simulating", "paused"].includes(plan.status));
  return <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Autonomous Operations</p><h2>Approval-gated autonomy</h2></div><span className="badge">deterministic</span></div><div className="grid twoColumn"><article><h3>Pending approvals</h3><ul>{(pending.length ? pending : []).map((a) => <li key={a.id}>{a.level}: {a.taskId} — {a.reason}</li>)}{!pending.length && <li>{empty}</li>}</ul></article><article><h3>Scheduled plans</h3><ul>{schedules.map((s) => <li key={s.id}>{s.planId}: {s.status} {s.nextRunAt ?? "waiting"}</li>)}{!schedules.length && <li>{empty}</li>}</ul></article><article><h3>Active autonomous sessions</h3><ul>{active.map((p) => <li key={p.id}>{p.title}: {p.status}</li>)}{!active.length && <li>{empty}</li>}</ul></article><article><h3>Recent autonomous executions</h3><ul>{plans.slice(0, 5).map((p) => <li key={p.id}>{p.id}: {p.tasks.length} tasks, confidence {p.confidence}%</li>)}{!plans.length && <li>{empty}</li>}</ul></article><article><h3>Retry queue</h3><ul>{retryQueue.map((r) => <li key={r.id}>{r.taskId}: attempt {r.attempt}, {r.classification}</li>)}{!retryQueue.length && <li>{empty}</li>}</ul></article><article><h3>Recovery queue</h3><ul>{recoveryQueue.map((r) => <li key={r.id}>{r.taskId}: {r.rollbackRequirement}</li>)}{!recoveryQueue.length && <li>{empty}</li>}</ul></article><article><h3>Approval history</h3><ul>{approvals.slice(0, 5).map((a) => <li key={a.id}>{a.status}: {a.taskId}</li>)}{!approvals.length && <li>{empty}</li>}</ul></article><article><h3>Execution timeline</h3><ul>{plans[0]?.timeline.map((t) => <li key={t.taskId}>#{t.order} {t.taskId} after {t.earliestStartOffsetMs / 1000}s</li>) ?? <li>{empty}</li>}</ul></article></div></section>;
}
