import { connectorError } from "../../../connector-errors";
import type { ConnectorExecutionRequest, ConnectorExecutionResult } from "../../../connector-types";
import { readiness } from "../shared/intelligence";
import { persistGoogleWorkspaceSnapshot } from "../shared/persistence";
import { recordGoogleWorkspaceTelemetry } from "../shared/telemetry";
import { requireWorkspaceEnvelope } from "../shared/types";
import { evaluateSheetsPolicy } from "./policy";
import { validateSheetsRequest } from "./validator";
const sampleCounters: Record<string, number> = {"trackers":5,"staleReports":2,"incompleteTrackers":1,"operationalGaps":1};
export async function executeSheetsOperation(request: ConnectorExecutionRequest): Promise<ConnectorExecutionResult> { const started=Date.now(); const validation=validateSheetsRequest(request); if(!validation.valid) return { connectorId:'google-sheets', operationId:request.operationId, success:false, error:connectorError('GOOGLE_WORKSPACE_CONTEXT_INVALID', validation.errors.join(' ')), durationMs:Date.now()-started, correlationId:request.context.correlationId }; const approved = request.input?.approved === true || request.context.metadata?.approved === true; const policy=evaluateSheetsPolicy(request.operationId, approved); if(!policy.allowed){ recordGoogleWorkspaceTelemetry({service:'sheets', operationId:request.operationId, status:'denied', durationMs:Date.now()-started, correlationId:request.context.correlationId, at:new Date().toISOString()}); return { connectorId:'google-sheets', operationId:request.operationId, success:false, error:connectorError('APPROVAL_REQUIRED', policy.reason), durationMs:Date.now()-started, correlationId:request.context.correlationId }; } const envelope=requireWorkspaceEnvelope(request.context,'google-sheets',request.operationId); const snapshot=persistGoogleWorkspaceSnapshot(readiness('sheets', sampleCounters)); const durationMs=Date.now()-started; recordGoogleWorkspaceTelemetry({service:'sheets', operationId:request.operationId, status:'success', durationMs, correlationId:request.context.correlationId, at:new Date().toISOString(), details:{readinessScore:snapshot.readinessScore}}); return { connectorId:'google-sheets', operationId:request.operationId, success:true, output:{ service:'sheets', operation:request.operationId, envelope, snapshot, approval:policy, deterministicIntelligence:true, networkCalls:0 }, durationMs, correlationId:request.context.correlationId }; }
