import { recordOrchestrationEvent } from "../persistence";
import { createRuntimeEvent } from "./runtime-events";
import { runtimeRegistry } from "./runtime-registry";
import { createRuntimeResult } from "./runtime-result";
import { completeRuntimeSession, createRuntimeSession } from "./runtime-session";
import { runtimeTelemetry } from "./runtime-telemetry";
import type { RuntimeExecutionContext, RuntimePolicy, RuntimeSession } from "./runtime-types";
export type RuntimeExecutionRequest = { toolId: string; input: unknown; context: RuntimeExecutionContext; policy?: RuntimePolicy };
export class RuntimeExecutor { sessions: RuntimeSession[] = []; async execute(request: RuntimeExecutionRequest): Promise<RuntimeSession> { const session = createRuntimeSession(request.context); this.addEvent(session, "session.started", "Runtime session started."); this.addEvent(session, "tool.requested", `Tool ${request.toolId} requested.`, request.toolId); const validation = runtimeRegistry.validateTool(request.toolId, request.input, request.context, request.policy, session.toolsUsed.length); if (!validation.valid) this.addEvent(session, "policy.denied", validation.errors.join(" "), request.toolId); else this.addEvent(session, "tool.validated", `Tool ${request.toolId} validated.`, request.toolId); const result = await runtimeRegistry.executeTool(request.toolId, request.input, request.context, request.policy, session.toolsUsed.length); session.toolsUsed.push(request.toolId); if (result.success) { this.addEvent(session, "tool.executed", `Tool ${request.toolId} executed.`, request.toolId); this.addEvent(session, "tool.completed", `Tool ${request.toolId} completed.`, request.toolId); } else { session.errors.push(result.error!); this.addEvent(session, "tool.failed", result.error?.message ?? "Tool failed.", request.toolId); } const runtimeResult = createRuntimeResult(session.id, session.startedAt, [result]); const completed = completeRuntimeSession(session, runtimeResult); this.addEvent(completed, "runtime.completed", `Runtime completed with ${runtimeResult.success ? "success" : "failure"}.`); this.sessions.push(completed); runtimeTelemetry.recordSession(completed); await this.persist(completed); return completed; } private addEvent(session: RuntimeSession, type: Parameters<typeof createRuntimeEvent>[0], message: string, toolId?: string) { const event = createRuntimeEvent(type, { sessionId: session.id, toolId, organizationId: session.organizationId, agentId: session.agentId, workflowId: session.workflowId, message }); session.events.push(event); session.timeline.push(event); runtimeTelemetry.recordEvent(event); } private async persist(session: RuntimeSession) { for (const event of session.events) await recordOrchestrationEvent({ token: session.context.accessToken, organizationId: session.organizationId, profileId: session.userId, correlationId: session.id }, { id: event.id, type: "health.updated", timestamp: event.timestamp, organizationId: event.organizationId, agentId: event.agentId, workflowId: event.workflowId, payload: event.payload ?? { message: event.message, toolId: event.toolId } }); } }
export const runtimeExecutor = new RuntimeExecutor();
