import { buildKnowledgeHealthReport, knowledgeRegistry } from "../knowledge";
import { workflowEngine } from "../workflows";
import { runtimeExecutor } from "./runtime-executor";
import { runtimeRegistry } from "./runtime-registry";
import { runtimeTelemetry } from "./runtime-telemetry";
import type { RuntimeToolDefinition } from "./runtime-types";
const schema = { object: (properties: Record<string, any> = {}, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: true }), string: { type: "string" }, boolean: { type: "boolean" } };
const base = { version: "1.0.0", organizationScope: "organization" as const, deterministic: true, supportsStreaming: false, supportsAsync: false, health: "healthy" as const, timeoutMs: 1000, retryPolicy: { maxRetries: 0, backoffMs: 0 }, securityClassification: "internal" as const };
export const builtInRuntimeTools: RuntimeToolDefinition[] = [
 { ...base, id: "runtime.echo", name: "Echo Tool", description: "Returns the provided message.", category: "utility", requiredPermissions: ["runtime:execute"], inputSchema: schema.object({ message: schema.string }, ["message"]), outputSchema: schema.object({ message: schema.string }, ["message"]), execute: (input) => ({ message: (input as {message:string}).message }) },
 { ...base, id: "runtime.json-validator", name: "JSON Validator", description: "Validates whether text is parseable JSON.", category: "utility", requiredPermissions: ["runtime:execute"], inputSchema: schema.object({ text: schema.string }, ["text"]), outputSchema: schema.object({ valid: schema.boolean }), execute: (input) => { try { JSON.parse((input as {text:string}).text); return { valid: true }; } catch (error) { return { valid: false, error: error instanceof Error ? error.message : String(error) }; } } },
 { ...base, id: "runtime.text-formatter", name: "Text Formatter", description: "Formats text as upper, lower, or title case.", category: "utility", requiredPermissions: ["runtime:execute"], inputSchema: schema.object({ text: schema.string, format: schema.string }, ["text"]), outputSchema: schema.object({ text: schema.string }), execute: (input) => { const { text, format } = input as {text:string; format?: string}; const formatted = format === "upper" ? text.toUpperCase() : format === "lower" ? text.toLowerCase() : text.replace(/\w\S*/g, (w) => w[0].toUpperCase() + w.slice(1).toLowerCase()); return { text: formatted }; } },
 { ...base, id: "runtime.organization-context", name: "Organization Context Tool", description: "Returns organization runtime context.", category: "organization", requiredPermissions: ["dashboard:read"], inputSchema: schema.object(), outputSchema: schema.object(), execute: (_input, context) => ({ organizationId: context.organizationId, userId: context.userId, agentId: context.agentId }) },
 { ...base, id: "runtime.workflow-summary", name: "Workflow Summary Tool", description: "Summarizes registered workflows.", category: "workflow", requiredPermissions: ["dashboard:read"], inputSchema: schema.object(), outputSchema: schema.object(), execute: () => ({ workflows: workflowEngine.listWorkflows().map((w) => ({ id: w.id, name: w.name, status: w.status, state: w.currentState })) }) },
 { ...base, id: "runtime.knowledge-summary", name: "Knowledge Summary Tool", description: "Summarizes Knowledge OS health.", category: "knowledge", requiredPermissions: ["knowledge:read"], inputSchema: schema.object(), outputSchema: schema.object(), execute: () => buildKnowledgeHealthReport(knowledgeRegistry) },
 { ...base, id: "runtime.health", name: "Runtime Health Tool", description: "Returns deterministic runtime health metrics.", category: "runtime", requiredPermissions: ["runtime:read"], inputSchema: schema.object(), outputSchema: schema.object(), execute: () => runtimeTelemetry.metrics() },
];
export function registerBuiltInRuntimeTools() { for (const tool of builtInRuntimeTools) if (!runtimeRegistry.getTool(tool.id)) runtimeRegistry.registerTool(tool); }
registerBuiltInRuntimeTools();
export const aiRuntime = { registry: runtimeRegistry, executor: runtimeExecutor, telemetry: runtimeTelemetry, registerBuiltInRuntimeTools };
