-- Milestone 6.2: Persistent execution, audit, and operating history.
create extension if not exists pgcrypto;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create table if not exists public.command_executions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text, correlation_id text, status text not null default 'queued', command_text text, payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.workflow_executions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text not null, execution_id text, correlation_id text, status text not null default 'queued', payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.workflow_execution_steps (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text not null, execution_id text not null, step_name text not null, correlation_id text, status text not null default 'queued', payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.orchestration_messages (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text, correlation_id text, status text not null default 'queued', message_type text, sender_agent_id text, recipient_agent_id text, payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.orchestration_tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text, correlation_id text, task_id text, status text not null default 'queued', payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.orchestration_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text, correlation_id text, event_type text, task_id text, status text not null default 'succeeded', payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.health_snapshots (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text, correlation_id text, snapshot_type text not null, subject_id text, status text not null default 'unknown', payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.system_audit_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, created_by uuid references public.profiles(id) on delete set null, agent_id text, workflow_id text, correlation_id text, action text not null, entity_table text, entity_id text, status text not null default 'succeeded', payload jsonb not null default '{}'::jsonb, result jsonb not null default '{}'::jsonb, error_details jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);

create index if not exists command_executions_org_created_idx on public.command_executions(organization_id, created_at desc); create index if not exists command_executions_status_idx on public.command_executions(status); create index if not exists command_executions_correlation_idx on public.command_executions(correlation_id); create index if not exists command_executions_agent_idx on public.command_executions(agent_id); create index if not exists command_executions_workflow_idx on public.command_executions(workflow_id);
create index if not exists workflow_executions_org_created_idx on public.workflow_executions(organization_id, created_at desc); create index if not exists workflow_executions_status_idx on public.workflow_executions(status); create index if not exists workflow_executions_correlation_idx on public.workflow_executions(correlation_id); create index if not exists workflow_executions_agent_idx on public.workflow_executions(agent_id); create index if not exists workflow_executions_workflow_idx on public.workflow_executions(workflow_id);
create index if not exists workflow_execution_steps_org_created_idx on public.workflow_execution_steps(organization_id, created_at desc); create index if not exists workflow_execution_steps_status_idx on public.workflow_execution_steps(status); create index if not exists workflow_execution_steps_correlation_idx on public.workflow_execution_steps(correlation_id); create index if not exists workflow_execution_steps_workflow_idx on public.workflow_execution_steps(workflow_id);
create index if not exists orchestration_messages_org_created_idx on public.orchestration_messages(organization_id, created_at desc); create index if not exists orchestration_messages_status_idx on public.orchestration_messages(status); create index if not exists orchestration_messages_correlation_idx on public.orchestration_messages(correlation_id); create index if not exists orchestration_messages_agent_idx on public.orchestration_messages(agent_id); create index if not exists orchestration_messages_workflow_idx on public.orchestration_messages(workflow_id);
create index if not exists orchestration_tasks_org_created_idx on public.orchestration_tasks(organization_id, created_at desc); create index if not exists orchestration_tasks_status_idx on public.orchestration_tasks(status); create index if not exists orchestration_tasks_correlation_idx on public.orchestration_tasks(correlation_id); create index if not exists orchestration_tasks_agent_idx on public.orchestration_tasks(agent_id); create index if not exists orchestration_tasks_workflow_idx on public.orchestration_tasks(workflow_id);
create index if not exists orchestration_events_org_created_idx on public.orchestration_events(organization_id, created_at desc); create index if not exists orchestration_events_status_idx on public.orchestration_events(status); create index if not exists orchestration_events_correlation_idx on public.orchestration_events(correlation_id); create index if not exists orchestration_events_agent_idx on public.orchestration_events(agent_id); create index if not exists orchestration_events_workflow_idx on public.orchestration_events(workflow_id);
create index if not exists health_snapshots_org_created_idx on public.health_snapshots(organization_id, created_at desc); create index if not exists health_snapshots_status_idx on public.health_snapshots(status); create index if not exists health_snapshots_correlation_idx on public.health_snapshots(correlation_id); create index if not exists health_snapshots_agent_idx on public.health_snapshots(agent_id); create index if not exists health_snapshots_workflow_idx on public.health_snapshots(workflow_id);
create index if not exists system_audit_events_org_created_idx on public.system_audit_events(organization_id, created_at desc); create index if not exists system_audit_events_status_idx on public.system_audit_events(status); create index if not exists system_audit_events_correlation_idx on public.system_audit_events(correlation_id); create index if not exists system_audit_events_agent_idx on public.system_audit_events(agent_id); create index if not exists system_audit_events_workflow_idx on public.system_audit_events(workflow_id);

alter table public.command_executions enable row level security; alter table public.workflow_executions enable row level security; alter table public.workflow_execution_steps enable row level security; alter table public.orchestration_messages enable row level security; alter table public.orchestration_tasks enable row level security; alter table public.orchestration_events enable row level security; alter table public.health_snapshots enable row level security; alter table public.system_audit_events enable row level security;

do $$ declare t text; begin foreach t in array array['command_executions','workflow_executions','workflow_execution_steps','orchestration_messages','orchestration_tasks','orchestration_events','health_snapshots','system_audit_events'] loop execute format('drop policy if exists %I_org_member_select on public.%I', t, t); execute format('create policy %I_org_member_select on public.%I for select using (public.is_org_member(organization_id, auth.uid()))', t, t); execute format('drop policy if exists %I_org_member_insert on public.%I', t, t); execute format('create policy %I_org_member_insert on public.%I for insert with check (public.is_org_member(organization_id, auth.uid()))', t, t); execute format('drop policy if exists %I_org_member_update on public.%I', t, t); execute format('create policy %I_org_member_update on public.%I for update using (public.is_org_member(organization_id, auth.uid())) with check (public.is_org_member(organization_id, auth.uid()))', t, t); execute format('drop trigger if exists %I_touch_updated_at on public.%I', t, t); execute format('create trigger %I_touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()', t, t); end loop; end $$;
